In [34]:
import numpy as np
import pandas as pd

In [35]:
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

In [36]:
df = pd.read_csv('../data/raw/flats.csv')
df.sample(5)

,property_name,link,society,price,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating,property_id
2620,3 BHK Flat in Sector 89 Gurgaon,https://www.99acres.com/3-bhk-bedroom-apartmen...,Smart World Gems,1.2 Crore,"₹ 8,433/sq.ft.",Built Up area: 1423 (132.2 sq.m.)Carpet area: ...,3 Bedrooms,3 Bathrooms,2 Balconies,NaN,"Sector 89, Sector 89 Gurgaon, Gurgaon, Haryana",2nd of 2 Floors,East,undefined,"['Sant Soordas Sihi Metro Station', 'Airia Mal...",Smartworld gems or m3m solitude sector 89 smar...,NaN,NaN,"['Environment4 out of 5', 'Safety4 out of 5', ...",C69125920
1225,3 BHK Flat in Sector 102 Gurgaon,https://www.99acres.com/3-bhk-bedroom-apartmen...,Conscient Heritage Max4.3 ★,2.1 Crore,"₹ 9,772/sq.ft.",Super Built up area 2149(199.65 sq.m.),3 Bedrooms,4 Bathrooms,3+ Balconies,"Study Room,Servant Room","N/a, Sector 102 Gurgaon, Gurgaon, Haryana",10th of 25 Floors,East,1 to 5 Year Old,"['Huda Metro Station', 'Ocus Medley Mall', 'Th...",Conscient heritage max is one of the most popu...,[],"['Power Back-up', 'Security / Fire Alarm', 'In...","['Green Area5 out of 5', 'Construction5 out of...",C69124616
2559,3 BHK Flat in Sector 37D Gurgaon,https://www.99acres.com/3-bhk-bedroom-apartmen...,Ramprastha The Edge Towers3.5 ★,1 Crore,"₹ 5,649/sq.ft.",Super Built up area 1770(164.44 sq.m.),3 Bedrooms,3 Bathrooms,3+ Balconies,NaN,"Sector 37D Gurgaon, Gurgaon, Haryana",13rd of 19 Floors,NaN,5 to 10 Year Old,"['MDS Public School', 'St Pauls School', 'Sunc...",It semi- Furnished wardrobes and modular kitchen,[],"['Power Back-up', 'Intercom Facility', 'Lift(s...","['Green Area4 out of 5', 'Construction4 out of...",U68986472
1882,4 BHK Flat in Sector 62 Gurgaon,https://www.99acres.com/4-bhk-bedroom-apartmen...,Pioneer Araya3.8 ★,9.95 Crore,"₹ 20,995/sq.ft.",Super Built up area 4739(440.27 sq.m.)Carpet a...,4 Bedrooms,6 Bathrooms,3 Balconies,"Pooja Room,Servant Room","Sector 62 Gurgaon, Gurgaon, Haryana",12nd of 34 Floors,South-East,1 to 5 Year Old,"['Paras Trinity Shopping Mall', 'Golf Course E...",Living at the 54 really is like living in a wo...,"['6 Fan', '10 Light', '7 AC', '1 Chimney', '1 ...","['Security / Fire Alarm', 'Power Back-up', 'Pr...","['Green Area5 out of 5', 'Construction4 out of...",X69844094
1127,4 BHK Flat in Sector 65 Gurgaon,https://www.99acres.com/4-bhk-bedroom-apartmen...,Emaar MGF Emerald Floors Premier3.8 ★,3 Crore,"₹ 15,189/sq.ft.",Super Built up area 1975(183.48 sq.m.),4 Bedrooms,4 Bathrooms,3+ Balconies,Servant Room,"1975 Sq Ft Apartment, Sector 65 Gurgaon, Gurga...",2nd of 4 Floors,South-East,1 to 5 Year Old,"['WorldMark Gurgaon', 'Sohna Road', 'Golf Cour...",Emaar mgf emerald floors premier is one of the...,NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Green Area4.5 out of 5', 'Construction5 out ...",X69449836

In [37]:
# shape
df.shape

(3028, 20)

In [38]:
# info
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3028 entries, 0 to 3027
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   property_name    3028 non-null   object
 1   link             3028 non-null   object
 2   society          3027 non-null   object
 3   price            3008 non-null   object
 4   area             3015 non-null   object
 5   areaWithType     3009 non-null   object
 6   bedRoom          3009 non-null   object
 7   bathroom         3009 non-null   object
 8   balcony          3009 non-null   object
 9   additionalRoom   1695 non-null   object
 10  address          3003 non-null   object
 11  floorNum         3007 non-null   object
 12  facing           2128 non-null   object
 13  agePossession    3008 non-null   object
 14  nearbyLocations  2914 non-null   object
 15  description      3009 non-null   object
 16  furnishDetails   2204 non-null   object
 17  features         2595 non-null   object
 18  rating           2677 non-null   object
 19  property_id      3009 non-null   object
dtypes: object(20)
memory usage: 473.2+ KB

In [39]:
# check for duplicates
df.duplicated().sum()

np.int64(0)

In [40]:
# check for missing values
df.isnull().sum()

property_name         0
link                  0
society               1
price                20
area                 13
areaWithType         19
bedRoom              19
bathroom             19
balcony              19
additionalRoom     1333
address              25
floorNum             21
facing              900
agePossession        20
nearbyLocations     114
description          19
furnishDetails      824
features            433
rating              351
property_id          19
dtype: int64

In [41]:
# Columns to drop -> property_name, link, property_id
df.drop(columns=['link','property_id'], inplace=True)

In [42]:
df.head()

,property_name,society,price,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Krishna Colony,maa bhagwati residency,45 Lac,"₹ 5,000/sq.ft.",Carpet area: 900 (83.61 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"Krishna Colony, Gurgaon, Haryana",4th of 4 Floors,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ..."
1,2 BHK Flat in Ashok Vihar,Apna Enclave,50 Lac,"₹ 7,692/sq.ft.",Carpet area: 650 (60.39 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"46b, Ashok Vihar, Gurgaon, Haryana",1st of 3 Floors,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ..."
2,2 BHK Flat in Sohna,Tulsiani Easy in Homes,40 Lac,"₹ 6,722/sq.ft.",Carpet area: 595 (55.28 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,NaN,"Sohna, Gurgaon, Haryana",12nd of 14 Floors,NaN,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment4 out of 5', 'Safety4 out of 5', ..."
3,2 BHK Flat in Sector 61 Gurgaon,Smart World Orchard,1.47 Crore,"₹ 12,250/sq.ft.",Carpet area: 1200 (111.48 sq.m.),2 Bedrooms,2 Bathrooms,2 Balconies,Study Room,"Sector 61 Gurgaon, Gurgaon, Haryana",2nd of 4 Floors,NaN,Dec 2023,"['Sector 55-56 Metro station', 'Bestech Centra...",Near to metro station of sector 56 and opposit...,NaN,"['Security / Fire Alarm', 'Private Garden / Te...",NaN
4,2 BHK Flat in Sector 92 Gurgaon,Parkwood Westend,70 Lac,"₹ 5,204/sq.ft.",Super Built up area 1345(124.95 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,Study Room,"Sector 92 Gurgaon, Gurgaon, Haryana",5th of 8 Floors,NaN,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",We are the proud owners of this 2 bhk alongwit...,[],NaN,"['Environment5 out of 5', 'Safety3 out of 5', ..."

In [43]:
# rename columns
df.rename(columns={'area':'price_per_sqft'},inplace=True)
df.head()

,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Krishna Colony,maa bhagwati residency,45 Lac,"₹ 5,000/sq.ft.",Carpet area: 900 (83.61 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"Krishna Colony, Gurgaon, Haryana",4th of 4 Floors,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ..."
1,2 BHK Flat in Ashok Vihar,Apna Enclave,50 Lac,"₹ 7,692/sq.ft.",Carpet area: 650 (60.39 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"46b, Ashok Vihar, Gurgaon, Haryana",1st of 3 Floors,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ..."
2,2 BHK Flat in Sohna,Tulsiani Easy in Homes,40 Lac,"₹ 6,722/sq.ft.",Carpet area: 595 (55.28 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,NaN,"Sohna, Gurgaon, Haryana",12nd of 14 Floors,NaN,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment4 out of 5', 'Safety4 out of 5', ..."
3,2 BHK Flat in Sector 61 Gurgaon,Smart World Orchard,1.47 Crore,"₹ 12,250/sq.ft.",Carpet area: 1200 (111.48 sq.m.),2 Bedrooms,2 Bathrooms,2 Balconies,Study Room,"Sector 61 Gurgaon, Gurgaon, Haryana",2nd of 4 Floors,NaN,Dec 2023,"['Sector 55-56 Metro station', 'Bestech Centra...",Near to metro station of sector 56 and opposit...,NaN,"['Security / Fire Alarm', 'Private Garden / Te...",NaN
4,2 BHK Flat in Sector 92 Gurgaon,Parkwood Westend,70 Lac,"₹ 5,204/sq.ft.",Super Built up area 1345(124.95 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,Study Room,"Sector 92 Gurgaon, Gurgaon, Haryana",5th of 8 Floors,NaN,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",We are the proud owners of this 2 bhk alongwit...,[],NaN,"['Environment5 out of 5', 'Safety3 out of 5', ..."

In [44]:
# society
df['society'].value_counts()

society
SS The Leaf3.8 ★                                     73
Tulip Violet4.3 ★                                    40
Shapoorji Pallonji Joyville Gurugram4.0 ★            39
Signature Global Park4.0 ★                           36
Shree Vardhman Victoria3.8 ★                         35
Tulip Violet4.2 ★                                    33
Emaar MGF Emerald Floors Premier3.8 ★                32
Smart World Gems                                     32
Smart World Orchard                                  32
DLF The Ultima4.0 ★                                  31
Paras Dews                                           31
DLF Regal Gardens3.9 ★                               30
M3M Woodshire4.0 ★                                   29
Shree Vardhman Flora3.8 ★                            29
La Vida by Tata Housing                              28
Signature Global Solera3.7 ★                         28
Godrej Nature Plus                                   27
Emaar Gurgaon Greens4.1 ★                            25
BPTP Terra3.8 ★                                      25
Eldeco Accolade3.8 ★                                 24
DLF New Town Heights 13.9 ★                          24
Experion The Heartsong3.9 ★                          24
Vatika Gurgaon 213.7 ★                               24
Bestech Park View Residency3.9 ★                     23
Tata Primanti4.1 ★                                   22
Emaar Palm Gardens4.1 ★                              22
ATS Triumph3.9 ★                                     22
M3M Heights                                          22
ROF Ananda                                           21
Sare Crescent Parc3.5 ★                              21
Experion Windchants3.8 ★                             20
Godrej 1014.0 ★                                      20
Antriksh Heights3.7 ★                                19
Supertech Araville                                   19
Sare Homes                                           19
ATS Tourmaline3.9 ★                                  18
Mapsko Mount Ville4.1 ★                              18
Ambience Creacions                                   18
Sobha City                                           18
Indiabulls Centrum Park3.7 ★                         18
CHD Avenue 713.6 ★                                   18
Conscient Heritage Max4.3 ★                          17
M3M Golfestate4.4 ★                                  17
M3M Skywalk                                          17
Godrej Summit3.7 ★                                   17
GLS Arawali Homes3.8 ★                               17
Pareena Coban Residences                             17
Umang Monsoon Breeze                                 16
HCBS Sports Ville3.6 ★                               16
Godrej Oasis3.9 ★                                    16
M3M Merlin3.7 ★                                      16
Bestech Park View Grand Spa4.3 ★                     16
Ansal Heights 86                                     15
Corona Optus3.9 ★                                    15
Emaar MGF The Palm Drive4.1 ★                        15
Ireo Skyon4.0 ★                                      14
MVN Athens3.7 ★                                      14
The Close North4.0 ★                                 14
DLF The Primus3.9 ★                                  14
Umang Winter Hills3.9 ★                              14
Ireo Victory Valley4.1 ★                             14
Ramsons Kshitij3.7 ★                                 14
Vatika The Seven Lamps3.8 ★                          14
Imperia The Esfera                                   14
Orchid Petals4.1 ★                                   14
Indiabulls Enigma                                    14
Central Park Flower Valley                           13
Bestech Park View Ananda4.2 ★                        13
Ireo The Corridors                                   13
Puri Emerald Bay3.7 ★                                13
SBTL Caladium                                        11
Adani M2K Oyster Grande3.9 ★                         11
Raheja Vedaanta3.6 ★                                 11
Godrej Aria3.8 ★                                     11
Breez Global Hill View                               11
DLF The Skycourt4.2 ★                                11
TARC Maceo3.8 ★                                      11
Alpha Corp GurgaonOne 844.0 ★                        11
M3M Soulitude                                        11
Signature Global Synera3.4 ★                         10
Capital Residences 360                               10
ATS Kocoon                                           10
Pivotal Devaan                                       10
Breez Global Heights4.2 ★                            10
Emaar MGF Palm Hills4.0 ★                            10
Ramprastha The Edge Towers3.5 ★                      10
Zara Aavaas                                          10
ILD Greens4.1 ★                                      10
Puri Diplomatic Greens4.0 ★                          10
Godrej Air                                           10
DLF New Town Heights 24.0 ★                          10
Pyramid Urban Homes 2                                10
Vatika City4.1 ★                                      9
AIPL The Peaceful Homes3.9 ★                          9
Pareena Mi Casa                                       9
Bestech Park View Sanskruti4.2 ★                      9
Parsvnath Green Ville3.9 ★                            9
Microtek Greenburg3.8 ★                               9
Tulip Ivory3.5 ★                                      8
AVL 36 Gurgaon3.7 ★                                   8
M3M Skycity                                           8
Birla Navya                                           8
ss                                                    8
Emaar Digihomes                                       8
Vatika Lifestyle Homes3.8 ★                           8
Assotech Blith                                        8
The Lions CGHS                                        8
Bestech Altura                                        8
Orris Aster Court Premier                             8
M3M Capital                                           8
GLS Avenue 51                                         8
Signature Andour Heights3.8 ★                         7
Signature Global City                                 7
AIPL Zen Residences                                   7
Ansal Housing Highland Park                           7
Signature Global Orchard Avenue3.6 ★                  7
Trisara Our Homes 3                                   7
Emaar Imperial Gardens3.8 ★                           7
Sare Crescent Parc Royal Greens Phase 1               7
Mapsko Casa Bella3.8 ★                                7
Orris Carnation Residency3.7 ★                        7
Ireo The Grand Arch4.0 ★                              7
Vipul Lavanya3.9 ★                                    7
Sare Green ParC Phase 3                               7
M3M Sierra 68                                         6
Supertech Hues                                        6
Shapoorji Pallonji Joyville Gurugram                  6
Ashiana Mulberry                                      6
DLF Regency Park 13.6 ★                               6
Signature Global City 63A                             6
Bestech Park View City4.1 ★                           6
Signature Global Park 4                               6
Signature The Roselia3.6 ★                            6
Pyramid Urban                                         6
Pioneer Araya3.8 ★                                    6
Suncity Vatsal Valley                                 6
Parsvnath Exotica3.7 ★                                6
BPTP Astaire Gardens3.7 ★                             6
Bestech Park View Spa Next4.0 ★                       6
Hero Homes                                            6
Kiran Residency                                       6
Sidhartha NCR One Phase 14.2 ★                        6
Greenopolis                                           6
Mapsko Royale Ville3.7 ★                              6
HSIIDC Sidco Aravali                                  6
Vatika Sovereign Park                                 5
Ireo Uptown4.1 ★                                      5
DLF Park Place4.1 ★                                   5
Central Park Flower Valley Aqua Front Towers          5
Signature Global Grand IVA3.9 ★                       5
Pioneer Park3.8 ★                                     5
Essel Towers                                          5
Satya The Hermitage3.5 ★                              5
Vatika City Homes3.9 ★                                5
Pareena Laxmi Apartments3.6 ★                         5
Green Court3.7 ★                                      5
Emaar MGF Emerald Estate3.8 ★                         5
Conscient Elevate                                     5
Signature Global City 37D Ph 2                        5
Adani Brahma Samsara Vilasa                           5
ATS Marigold                                          5
Krisumi Waterfall Residences                          5
DLF Regency Park 24.0 ★                               5
Signature Global City 92                              5
Tulip Monsella                                        5
Godrej Habitat                                        5
Central Park Resorts4.4 ★                             5
Ashiana Anmol3.5 ★                                    5
Signature Global the Millennia                        5
M3M The Marina4.0 ★                                   5
Silverglades The Melia                                5
Signature Global City 81                              5
Apna Enclave                                          5
Unitech Fresco3.8 ★                                   4
Ramprastha Primera                                    4
Sare Petioles                                         4
Raheja Navodaya3.6 ★                                  4
Unitech Vistas                                        4
Ramprastha Skyz                                       4
Prime Habitat                                         4
Lotus Homz4.0 ★                                       4
Corona Gracieux                                       4
Godrej Frontier3.7 ★                                  4
Tata Gurgaon Gateway3.8 ★                             4
Krrish Provence Estate                                4
Emaar Palm Heights                                    4
HSIIDC Sidco Shivalik Apartments3.8 ★                 4
DLF New Town Heights3.7 ★                             4
DLF The Skycourt                                      4
Signature The Serenas                                 4
Godrej Icon                                           4
Orris Aster Court                                     4
SS The Coralwood3.4 ★                                 4
ILD Grand                                             4
Railway Officers RPF Society                          4
Global Hill View                                      4
Pivotal Riddhi Siddhi                                 3
Spaze Privvy The Address3.9 ★                         3
DLF Express Greens3.9 ★                               3
Whiteland Blissville                                  3
Sukhshanti Apartment                                  3
AIPL Club Residences                                  3
DLF The Grove                                         3
Raheja Sampada                                        3
Bestech Park View City 23.9 ★                         3
Shri Banke Bihari Society3.8 ★                        3
Brisk Lumbini Terrace Homes                           3
Tulip Purple                                          3
Unitech Heritage City                                 3
Vatika Independent Floors3.8 ★                        3
Tulip White3.5 ★                                      3
Jammu and Kashmir Bank Employees CGHS3.7 ★            3
Guru Gram Haryana CGHS4.1 ★                           3
Unitech The Residences3.7 ★                           3
Raheja Revanta                                        3
DLF Royalton Tower                                    3
AFNHB Jalvayu Vihar3.7 ★                              3
Maxworth City Residences                              3
Sare Green Parc 2                                     3
Essel Tower                                           3
Smriti Apartment                                      3
Paras Quartier                                        3
Ambience Lagoon3.9 ★                                  3
DLF Belvedere Towers3.8 ★                             3
Deepak Minda                                          3
Sare Green Parc                                       3
Adani Aangan Arcade                                   3
Vatika Xpressions                                     3
Siddhartha Apartment                                  3
Piedmont Taksila heights3.6 ★                         3
Krrish Florence Estate                                3
Tulip Lemon3.9 ★                                      3
Sunischit Apartments                                  3
Dhoot Time Residency4.0 ★                             3
ATS Kocoon4.2 ★                                       3
The Roselia 2                                         3
Shree Arihant Apartment                               3
Conscient Habitat3.6 ★                                3
Mahindra Aura4.2 ★                                    3
Apex Our Homes                                        3
Spaze Privy AT43.9 ★                                  3
Puri Diplomatic Greens3.9 ★                           3
Suncity Platinum Towers                               3
Chintels Paradiso3.9 ★                                3
Valley View Estate                                    3
DLF The Arbour                                        3
Sidhartha NCR Greens4.3 ★                             3
Tulip Petals3.6 ★                                     3
Spaze Privy3.9 ★                                      3
My Home                                               3
Pyramid Elite                                         3
Kendriya Vihar4.1 ★                                   3
Satya Element One                                     3
Shri Ram Apartments                                   3
Unitech Sunbreeze                                     3
Signature Global Solera 2                             3
Sapphire Eighty Three                                 3
DLF Carlton Estate4.0 ★                               3
Unitech Uniworld Gardens3.8 ★                         3
SS Almeria                                            3
Raheja Atharva3.6 ★                                   3
Sidhartha NCR One                                     3
Oriental Valley CHS                                   2
Aqua Front Towers                                     2
Vatika INXT Floors                                    2
MRG World Ultimus                                     2
BPTP Pedestal                                         2
M3M Urbana                                            2
Landmark The Residency                                2
Vasant Appartments                                    2
Raheja Vanya                                          2
Mapsko Paradise3.9 ★                                  2
Ramprastha The Atrium3.4 ★                            2
Park Royal Apartment                                  2
The Close South3.9 ★                                  2
lagoon apartment                                      2
Samaspurkunj                                          2
Residency Grand                                       2
Uphar lakshya homes                                   2
Godrej Aria , sector 79 , Gurgaon                     2
ss residency                                          2
Emaar MGF The Enclave                                 2
Chanderlok Society                                    2
Tulsiani Easy in Homes                                2
Vipul Belmonte3.9 ★                                   2
BPTP Freedom Park Life4.0 ★                           2
Maruti Vihar                                          2
Mahindra Luminare4.0 ★                                2
Ganga Apartment                                       2
Supertech Hill Town                                   2
NBCC Heights3.9 ★                                     2
Mittal Surya Vihar                                    2
Palam Vihar Society                                   2
Ansal Heights3.2 ★                                    2
Supertech Hilltown                                    2
Professors Enclave CGHS                               2
DLF The Crest3.6 ★                                    2
Green Campus CHS                                      2
Today Callidora                                       2
Suncity Avenue 76                                     2
Sahara Grace                                          2
Housing Board Colony                                  2
Godrej Nature Plus Serenity                           2
Ashiana Anmol                                         2
Bestech Spa Signature                                 2
Unitech Uniworld Gardens 23.4 ★                       2
CGHS Airport Apartment                                2
AWHO Shanti Vihar4.0 ★                                2
Central Park 2 Bellevue                               2
Raheja Atlantis3.8 ★                                  2
ROF Aalayas3.8 ★                                      2
Elan The Presidential                                 2
Ansal API Esencia3.7 ★                                2
HCBS Sports Ville                                     2
Adani Aangan Galleria                                 2
Tulip Orange3.9 ★                                     2
M3M Ikonic                                            2
Bestech Park View Sanskruti4.1 ★                      2
Viridian The Plaza 106                                2
Suposhaa Smartworld Orchard                           2
Suncity Heights3.7 ★                                  2
DLF The Icon3.7 ★                                     2
Ansal API Celebrity Suites                            2
Ardee City3.8 ★                                       2
Breeze Global Heights                                 2
Sidhivinayak Apartments                               2
Bhagwati Sadan                                        2
Ramprastha City                                       2
Puri The Aravallis                                    2
Emaar MGF Palm Studios                                2
Signature Global The Millennia 3                      2
M3M Sky Lofts                                         2
Pioneer Urban Presidia                                2
M3M Latitude                                          2
The Penthouses at the Hibiscus                        2
Orchid Island4.2 ★                                    2
SS Hibiscus                                           2
Tulip Leaf                                            2
Tulip Violet                                          2
Vatika Emilia Floors3.7 ★                             2
BPTP Mansions Park Prime                              2
Dlf City                                              2
Silverglades Hightown Residences                      2
Surendra Avenue 69                                    2
Vipul World Floors                                    2
Milan CGHS 9                                          2
Element One Service                                   2
Shapoorji Pallonji Joyville                           2
Apartment                                             2
Ambience Caitriona                                    2
Lavanya Apartments                                    2
om appartments                                        2
Paras Irene3.7 ★                                      2
DLF The Belaire3.9 ★                                  2
Suncity Avenue 1023.9 ★                               2
BPTP Amstoria3.8 ★                                    2
Ansal Sushant Lok CI                                  1

In [45]:
df['society'].value_counts().shape

(639,)

In [46]:
import re
df['society'] = df['society'].apply(lambda name: re.sub(r'\d+(\.\d+)?\s?★', '', str(name)).strip()).str.lower()

In [47]:
df['society'].value_counts().shape

(605,)

In [48]:
df['society'].value_counts()

society
tulip violet                                     75
ss the leaf                                      74
shapoorji pallonji joyville gurugram             45
dlf new town heights                             38
signature global park                            36
shree vardhman victoria                          35
smart world gems                                 32
emaar mgf emerald floors premier                 32
smart world orchard                              32
paras dews                                       31
dlf the ultima                                   31
dlf regal gardens                                30
m3m woodshire                                    30
shree vardhman flora                             29
la vida by tata housing                          28
signature global solera                          28
godrej nature plus                               27
bptp terra                                       25
emaar gurgaon greens                             25
vatika gurgaon                                   24
experion the heartsong                           24
eldeco accolade                                  24
bestech park view residency                      23
m3m heights                                      22
ats triumph                                      22
emaar palm gardens                               22
tata primanti                                    22
sare crescent parc                               21
rof ananda                                       21
godrej                                           21
experion windchants                              20
sare homes                                       19
supertech araville                               19
antriksh heights                                 19
hcbs sports ville                                18
sobha city                                       18
chd avenue                                       18
m3m golfestate                                   18
indiabulls centrum park                          18
mapsko mount ville                               18
ats tourmaline                                   18
ambience creacions                               18
m3m skywalk                                      18
gls arawali homes                                17
godrej summit                                    17
conscient heritage max                           17
pareena coban residences                         17
godrej oasis                                     16
umang monsoon breeze                             16
bestech park view grand spa                      16
m3m merlin                                       16
corona optus                                     15
ramsons kshitij                                  15
ansal heights 86                                 15
dlf the skycourt                                 15
emaar mgf the palm drive                         15
umang winter hills                               14
indiabulls enigma                                14
mvn athens                                       14
imperia the esfera                               14
orchid petals                                    14
ireo victory valley                              14
vatika the seven lamps                           14
bestech park view ananda                         14
the close north                                  14
dlf the primus                                   14
ireo skyon                                       14
puri emerald bay                                 13
central park flower valley                       13
puri diplomatic greens                           13
ireo the corridors                               13
ats kocoon                                       13
tarc maceo                                       11
m3m soulitude                                    11
godrej aria                                      11
breez global heights                             11
bestech park view sanskruti                      11
alpha corp gurgaonone                            11
raheja vedaanta                                  11
ild greens                                       11
breez global hill view                           11
dlf regency park                                 11
adani m2k oyster grande                          11
sbtl caladium                                    11
zara aavaas                                      10
pyramid urban homes 2                            10
capital residences 360                           10
emaar mgf palm hills                             10
godrej air                                       10
signature global synera                          10
ramprastha the edge towers                       10
pivotal devaan                                   10
parsvnath green ville                             9
pareena mi casa                                   9
aipl the peaceful homes                           9
bestech park view city                            9
vatika city                                       9
microtek greenburg                                9
bestech altura                                    8
emaar digihomes                                   8
orris aster court premier                         8
m3m capital                                       8
the lions cghs                                    8
avl 36 gurgaon                                    8
vatika lifestyle homes                            8
tulip ivory                                       8
birla navya                                       8
gls avenue 51                                     8
assotech blith                                    8
ss                                                8
m3m skycity                                       8
ashiana anmol                                     7
orris carnation residency                         7
vipul lavanya                                     7
signature andour heights                          7
signature global city                             7
ansal housing highland park                       7
signature global orchard avenue                   7
ireo the grand arch                               7
mapsko casa bella                                 7
emaar imperial gardens                            7
sidhartha ncr one phase                           7
trisara our homes 3                               7
sare green parc phase 3                           7
aipl zen residences                               7
sare crescent parc royal greens phase 1           7
signature global city 63a                         6
pyramid urban                                     6
green court                                       6
signature the roselia                             6
hero homes                                        6
signature global park 4                           6
parsvnath exotica                                 6
suncity vatsal valley                             6
kiran residency                                   6
bestech park view spa next                        6
mapsko royale ville                               6
bptp astaire gardens                              6
supertech hues                                    6
ashiana mulberry                                  6
m3m sierra 68                                     6
pioneer araya                                     6
greenopolis                                       6
hsiidc sidco aravali                              6
unitech fresco                                    5
vatika sovereign park                             5
apna enclave                                      5
pareena laxmi apartments                          5
satya the hermitage                               5
ireo uptown                                       5
signature global grand iva                        5
essel towers                                      5
central park flower valley aqua front towers      5
signature global city 81                          5
vatika city homes                                 5
krisumi waterfall residences                      5
conscient elevate                                 5
tulip monsella                                    5
adani brahma samsara vilasa                       5
pioneer park                                      5
signature global the millennia                    5
emaar mgf emerald estate                          5
ats marigold                                      5
dlf park place                                    5
signature global city 37d ph 2                    5
unitech uniworld gardens                          5
silverglades the melia                            5
godrej habitat                                    5
central park resorts                              5
m3m the marina                                    5
signature global city 92                          5
ramprastha primera                                4
prime habitat                                     4
tata gurgaon gateway                              4
afnhb jalvayu vihar                               4
ss the coralwood                                  4
krrish provence estate                            4
godrej icon                                       4
dlf the arbour                                    4
railway officers rpf society                      4
lotus homz                                        4
essel tower                                       4
emaar palm heights                                4
orris aster court                                 4
ild grand                                         4
global hill view                                  4
unitech vistas                                    4
kendriya vihar                                    4
raheja navodaya                                   4
godrej frontier                                   4
hsiidc sidco shivalik apartments                  4
signature the serenas                             4
ramprastha skyz                                   4
sare petioles                                     4
corona gracieux                                   4
suncity platinum towers                           3
spaze privy at                                    3
sidhartha ncr one                                 3
raheja sampada                                    3
ss residency                                      3
dlf royalton tower                                3
tulip lemon                                       3
spaze privy                                       3
deepak minda                                      3
maxworth city residences                          3
tulip white                                       3
ss almeria                                        3
sukhshanti apartment                              3
unitech sunbreeze                                 3
pivotal riddhi siddhi                             3
unitech heritage city                             3
chintels paradiso                                 3
signature global solera 2                         3
sare green parc                                   3
adani aangan arcade                               3
smriti apartment                                  3
conscient habitat                                 3
pyramid elite                                     3
brisk lumbini terrace homes                       3
the roselia 2                                     3
sidhartha ncr greens                              3
unitech the residences                            3
my home                                           3
valley view estate                                3
satya element one                                 3
bhagwati sadan                                    3
vatika xpressions                                 3
sunischit apartments                              3
guru gram haryana cghs                            3
dlf belvedere towers                              3
aipl club residences                              3
ambience lagoon                                   3
paras quartier                                    3
sapphire eighty three                             3
dlf the grove                                     3
shri ram apartments                               3
tulip petals                                      3
tulip purple                                      3
raheja atharva                                    3
whiteland blissville                              3
spaze privvy the address                          3
piedmont taksila heights                          3
krrish florence estate                            3
dlf carlton estate                                3
mahindra aura                                     3
shri banke bihari society                         3
shree arihant apartment                           3
dlf express greens                                3
sare green parc 2                                 3
vatika independent floors                         3
dhoot time residency                              3
jammu and kashmir bank employees cghs             3
apex our homes                                    3
siddhartha apartment                              3
raheja revanta                                    3
samaspurkunj                                      2
bptp freedom park life                            2
shapoorji pallonji joyville                       2
dlf city                                          2
element one service                               2
breeze global heights                             2
residency grand                                   2
apartment                                         2
om appartments                                    2
lavanya apartments                                2
suncity avenue                                    2
dlf the belaire                                   2
mrg world ultimus                                 2
adani aangan galleria                             2
landmark the residency                            2
mahindra luminare                                 2
signature global the millennia 3                  2
m3m sky lofts                                     2
raheja atlantis                                   2
mapsko paradise                                   2
sahara grace                                      2
orchid island                                     2
rof aalayas                                       2
awho shanti vihar                                 2
sidhivinayak apartments                           2
ansal api esencia                                 2
emaar mgf emerald floors                          2
oriental valley chs                               2
nbcc heights                                      2
supertech hill town                               2
godrej nature plus serenity                       2
ansal heights                                     2
m3m urbana                                        2
suncity avenue 76                                 2
suncity heights                                   2
lagoon apartment                                  2
palam vihar society                               2
maruti vihar                                      2
pioneer urban presidia                            2
m3m latitude                                      2
elan the presidential                             2
the close south                                   2
today callidora                                   2
bptp pedestal                                     2
park royal apartment                              2
central park 2 bellevue                           2
tulip orange                                      2
vasant appartments                                2
shyam apartment                                   2
housing board colony                              2
raheja vanya                                      2
paras irene                                       2
bptp mansions park prime                          2
cghs airport apartment                            2
bestech spa signature                             2
ansal api celebrity suites                        2
green campus chs                                  2
aqua front towers                                 2
ramprastha city                                   2
ardee city                                        2
ramprastha the atrium                             2
shree shyam residency                             2
ganga apartment                                   2
supertech hilltown                                2
vatika inxt floors                                2
mittal surya vihar                                2
suposhaa smartworld orchard                       2
dlf the crest                                     2
tulip leaf                                        2
vatika emilia floors                              2
viridian the plaza 106                            2
professors enclave cghs                           2
dlf the icon                                      2
puri the aravallis                                2
m3m ikonic                                        2
ss hibiscus                                       2
emaar mgf palm studios                            2
the penthouses at the hibiscus                    2
milan cghs 9                                      2
bptp amstoria                                     2
emaar mgf the enclave                             2
vipul belmonte                                    2
surendra avenue 69                                2
ambience caitriona                                2
vipul world floors                                2
silverglades hightown residences                  2
chanderlok society                                2
tulsiani easy in homes                            2
uphar lakshya homes                               2
godrej aria , sector 79 , gurgaon                 2
spire woods now ananda by alpha corp              1
senate court                                      1
signature global orchard avenue 2                 1
the new people apartments                         1
godrej summit premia towers                       1
godrej meridien                                   1
pooja apartment                                   1
gokuldham society, bahadurgarh                    1
4s aradhya homes                                  1
spectrum centre                                   1
vatika india next                                 1
imperia elvedor                                   1
emaar mgf palm terraces                           1
anamika enclave                                   1
huda ashok vihar phase                            1
emaar palm premier                                1
conscient one                                     1
not applicable                                    1
smartworld 1dxp                                   1
czar mahira homes 63a                             1
micasa sec 68                                     1
shyam sadan                                       1
hanumanta apartment                               1
ashiyara 2                                        1
m3m golf hills phase 1                            1
abhinav group housing society                     1
signature signum 95a                              1
aardhya homesh                                    1
pyramid pride                                     1
om apartment dayanand colony                      1
unitech south park                                1
the ivy                                           1
mrg skyline                                       1
m3m one key resiments                             1
sushant lok 1 builder floors                      1
vatika sovereign next sector-82 a gurgaon         1
kanchanjanga tower                                1
millenium bajrang society                         1
adani oyster greens                               1

In [49]:
df.head()

,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Krishna Colony,maa bhagwati residency,45 Lac,"₹ 5,000/sq.ft.",Carpet area: 900 (83.61 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"Krishna Colony, Gurgaon, Haryana",4th of 4 Floors,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ..."
1,2 BHK Flat in Ashok Vihar,apna enclave,50 Lac,"₹ 7,692/sq.ft.",Carpet area: 650 (60.39 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"46b, Ashok Vihar, Gurgaon, Haryana",1st of 3 Floors,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ..."
2,2 BHK Flat in Sohna,tulsiani easy in homes,40 Lac,"₹ 6,722/sq.ft.",Carpet area: 595 (55.28 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,NaN,"Sohna, Gurgaon, Haryana",12nd of 14 Floors,NaN,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment4 out of 5', 'Safety4 out of 5', ..."
3,2 BHK Flat in Sector 61 Gurgaon,smart world orchard,1.47 Crore,"₹ 12,250/sq.ft.",Carpet area: 1200 (111.48 sq.m.),2 Bedrooms,2 Bathrooms,2 Balconies,Study Room,"Sector 61 Gurgaon, Gurgaon, Haryana",2nd of 4 Floors,NaN,Dec 2023,"['Sector 55-56 Metro station', 'Bestech Centra...",Near to metro station of sector 56 and opposit...,NaN,"['Security / Fire Alarm', 'Private Garden / Te...",NaN
4,2 BHK Flat in Sector 92 Gurgaon,parkwood westend,70 Lac,"₹ 5,204/sq.ft.",Super Built up area 1345(124.95 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,Study Room,"Sector 92 Gurgaon, Gurgaon, Haryana",5th of 8 Floors,NaN,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",We are the proud owners of this 2 bhk alongwit...,[],NaN,"['Environment5 out of 5', 'Safety3 out of 5', ..."

In [50]:
# price
df['price'].value_counts()

price
1.25 Crore          79
1.1 Crore           61
1.4 Crore           60
1.2 Crore           59
1.5 Crore           59
90 Lac              58
1.3 Crore           57
95 Lac              53
2 Crore             51
1.75 Crore          47
1 Crore             46
1.6 Crore           43
1.35 Crore          41
1.55 Crore          40
1.9 Crore           40
75 Lac              38
1.65 Crore          38
1.8 Crore           37
1.7 Crore           37
80 Lac              36
2.2 Crore           34
1.15 Crore          33
50 Lac              33
1.45 Crore          31
85 Lac              31
1.05 Crore          30
2.5 Crore           29
40 Lac              29
60 Lac              29
2.1 Crore           26
45 Lac              26
65 Lac              25
1.85 Crore          23
2.35 Crore          23
35 Lac              23
3 Crore             22
70 Lac              21
2.25 Crore          20
55 Lac              20
3.5 Crore           19
2.4 Crore           18
2.3 Crore           18
30 Lac              17
2.65 Crore          16
1.38 Crore          15
2.6 Crore           15
3.4 Crore           14
2.15 Crore          14
2.45 Crore          14
3.25 Crore          13
92 Lac              13
78 Lac              13
1.32 Crore          13
38 Lac              13
2.7 Crore           13
82 Lac              13
5 Crore             12
2.8 Crore           12
1.42 Crore          12
42 Lac              12
1.95 Crore          12
32 Lac              11
25 Lac              11
1.08 Crore          11
Price on Request    11
88 Lac              11
28 Lac              10
87 Lac              10
26 Lac              10
1.78 Crore          10
1.12 Crore          10
1.28 Crore          10
2.55 Crore          10
2.85 Crore           9
3.45 Crore           9
4 Crore              9
1.72 Crore           9
22 Lac               9
36 Lac               9
1.68 Crore           9
2.05 Crore           9
99 Lac               9
56 Lac               8
6 Crore              8
1.76 Crore           8
1.54 Crore           8
6.5 Crore            8
98 Lac               8
86 Lac               8
1.26 Crore           8
1.18 Crore           8
4.25 Crore           8
20 Lac               8
27 Lac               8
48 Lac               8
3.2 Crore            8
2.75 Crore           8
79 Lac               7
1.99 Crore           7
2.9 Crore            7
72 Lac               7
1.02 Crore           7
39 Lac               7
97 Lac               7
3.3 Crore            7
3.7 Crore            7
1.36 Crore           7
46 Lac               7
1.27 Crore           7
1.19 Crore           7
1.29 Crore           7
96 Lac               6
2.95 Crore           6
1.16 Crore           6
37 Lac               6
3.05 Crore           6
3.9 Crore            6
1.51 Crore           6
1.01 Crore           6
21 Lac               6
43 Lac               6
3.35 Crore           6
54 Lac               6
1.39 Crore           6
1.13 Crore           6
1.34 Crore           6
1.07 Crore           6
1.14 Crore           6
71.5 Lac             6
4.1 Crore            6
1.59 Crore           6
1.98 Crore           6
1.49 Crore           6
3.65 Crore           6
5.5 Crore            6
4.5 Crore            5
68 Lac               5
1.62 Crore           5
93 Lac               5
1.92 Crore           5
1.83 Crore           5
64 Lac               5
1.79 Crore           5
24 Lac               5
1.44 Crore           5
1.91 Crore           5
1.69 Crore           5
1.17 Crore           5
2.22 Crore           5
1.24 Crore           5
2.29 Crore           5
66 Lac               5
1.43 Crore           5
1.82 Crore           5
1.93 Crore           5
6.75 Crore           5
2.12 Crore           5
1.33 Crore           5
49 Lac               5
2.78 Crore           5
3.75 Crore           5
29 Lac               5
1.47 Crore           5
67 Lac               4
33 Lac               4
1.23 Crore           4
1.77 Crore           4
3.6 Crore            4
36.5 Lac             4
1.71 Crore           4
2.09 Crore           4
1.22 Crore           4
1.64 Crore           4
5.9 Crore            4
1.66 Crore           4
74 Lac               4
73 Lac               4
89 Lac               4
41.5 Lac             4
28.5 Lac             4
4.3 Crore            4
3.1 Crore            4
7 Crore              4
4.85 Crore           4
31 Lac               4
1.31 Crore           4
1.37 Crore           4
1.52 Crore           4
1.73 Crore           4
58 Lac               4
3.95 Crore           4
6.15 Crore           4
1.58 Crore           4
62 Lac               4
1.48 Crore           4
5.25 Crore           4
5.6 Crore            4
1.63 Crore           3
5.8 Crore            3
72.5 Lac             3
2.01 Crore           3
1.21 Crore           3
2.36 Crore           3
64.5 Lac             3
1.88 Crore           3
1.57 Crore           3
34 Lac               3
51 Lac               3
84 Lac               3
83 Lac               3
2.08 Crore           3
1.09 Crore           3
69 Lac               3
2.03 Crore           3
1.67 Crore           3
2.51 Crore           3
4.8 Crore            3
2.79 Crore           3
2.33 Crore           3
3.8 Crore            3
2.28 Crore           3
1.04 Crore           3
3.49 Crore           3
1.41 Crore           3
91 Lac               3
2.24 Crore           3
3.85 Crore           3
52 Lac               3
3.15 Crore           3
94 Lac               3
47 Lac               3
4.2 Crore            3
4.75 Crore           3
41 Lac               2
4.55 Crore           2
71 Lac               2
87.5 Lac             2
59 Lac               2
11 Crore             2
7.5 Crore            2
27.1 Lac             2
2.04 Crore           2
3.29 Crore           2
1.46 Crore           2
8 Crore              2
8.5 Crore            2
2.13 Crore           2
2.17 Crore           2
1.56 Crore           2
2.26 Crore           2
2.99 Crore           2
2.87 Crore           2
2.57 Crore           2
5.2 Crore            2
3.21 Crore           2
4.6 Crore            2
2.23 Crore           2
6.2 Crore            2
1.87 Crore           2
3.32 Crore           2
4.26 Crore           2
2.52 Crore           2
4.49 Crore           2
53.5 Lac             2
53 Lac               2
31.5 Lac             2
2.91 Crore           2
77.5 Lac             2
25.5 Lac             2
5.7 Crore            2
2.14 Crore           2
2.58 Crore           2
52.56 Lac            2
27.75 Lac            2
4.7 Crore            2
4.45 Crore           2
88.5 Lac             2
2.02 Crore           2
2.41 Crore           2
14 Crore             2
98.5 Lac             2
56.2 Lac             2
3.55 Crore           2
7.52 Crore           1
95.5 Lac             1
70.85 Lac            1
19 Lac               1
96.07 Lac            1
94.99 Lac            1
86.92 Lac            1
2.86 Crore           1
16 Lac               1
29.99 Lac            1
57 Lac               1
3.72 Crore           1
88.4 Lac             1
4.52 Crore           1
4.16 Crore           1
4.21 Crore           1
8.44 Crore           1
13.2 Crore           1
2.92 Crore           1
2.38 Crore           1
32.5 Lac             1
7.8 Crore            1
15 Crore             1
39.5 Lac             1
1.97 Crore           1
4.02 Crore           1
6.25 Crore           1
40.3 Lac             1
82.5 Lac             1
4.95 Crore           1
8.25 Crore           1
3.67 Crore           1
2.21 Crore           1
89.5 Lac             1
2.48 Crore           1
99.5 Lac             1
3.83 Crore           1
2.72 Crore           1
49.5 Lac             1
7.9 Crore            1
3.23 Crore           1
66.99 Lac            1
4.78 Crore           1
6.16 Crore           1
5.3 Crore            1
86.99 Lac            1
87.99 Lac            1
9.2 Crore            1
9.95 Crore           1
85.75 Lac            1
1.86 Crore           1
97.04 Lac            1
1.84 Crore           1
97.5 Lac             1
2.64 Crore           1
2.49 Crore           1
63.4 Lac             1
2.06 Crore           1
2.07 Crore           1
44 Lac               1
2.32 Crore           1
1.53 Crore           1
2.96 Crore           1
61 Lac               1
4.79 Crore           1
55.5 Lac             1
7.56 Crore           1
6.44 Crore           1
1.11 Crore           1
80.5 Lac             1
93.75 Lac            1
85.5 Lac             1
68.5 Lac             1
79.9 Lac             1
29.5 Lac             1
94.25 Lac            1
2.97 Crore           1
3.63 Crore           1
3.39 Crore           1
4.67 Crore           1
2.37 Crore           1
95.75 Lac            1
2.98 Crore           1
3.46 Crore           1
5.4 Crore            1
55.6 Lac             1
98.1 Lac             1
2.63 Crore           1
price                1
3.19 Crore           1
4.4 Crore            1
4.63 Crore           1
5.31 Crore           1
37.5 Lac             1
2.54 Crore           1
2.69 Crore           1
54.8 Lac             1
31.75 Lac            1
3.98 Crore           1
23 Lac               1
1.06 Crore           1
9.14 Crore           1
26.1 Lac             1
81 Lac               1
8.35 Crore           1
4.94 Crore           1
10.75 Crore          1
35.5 Lac             1
23.5 Lac             1
3.87 Crore           1
27.5 Lac             1
71.2 Lac             1
54.99 Lac            1
6.1 Crore            1
5.75 Crore           1
10 Crore             1
2.11 Crore           1
24.5 Lac             1
2.82 Crore           1
7.15 Crore           1
11.25 Crore          1
3.79 Crore           1
2.34 Crore           1
6.3 Crore            1
5.49 Crore           1
65.5 Lac             1
2.61 Crore           1
42.5 Lac             1
2.77 Crore           1
20.5 Lac             1
47.5 Lac             1
17.5 Lac             1
90.5 Lac             1
4.86 Crore           1
2.62 Crore           1
5.15 Crore           1
9.3 Crore            1
6.02 Crore           1
1.74 Crore           1
52.5 Lac             1
53.2 Lac             1
29.8 Lac             1
94.5 Lac             1
2.44 Crore           1
9 Crore              1
3.99 Crore           1
64.45 Lac            1
37.1 Lac             1
7.4 Crore            1
3.78 Crore           1
98.88 Lac            1
68.85 Lac            1
26.9 Lac             1
26.5 Lac             1
73.53 Lac            1
89.77 Lac            1
62.5 Lac             1
Name: count, dtype: int64

In [51]:
df[df['price'] == 'Price on Request']

,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
25,5 BHK Flat in Sector 1 Gurgaon,the new people apartments,Price on Request,NaN,Built Up area: 4500 (418.06 sq.m.),5 Bedrooms,1 Bathroom,No Balcony,NaN,"Sector 1, Sector 1 Gurgaon, Gurgaon, Haryana",Ground of 1 Floors,NaN,undefined,"['Pooja Clinic', 'Dr. Sahil Clinic', 'Prakash ...",Best in class property available at sector 1 l...,NaN,NaN,NaN
1645,4 BHK Flat in Sector 50 Gurgaon,ss hibiscus,Price on Request,NaN,Carpet area: 4800 (445.93 sq.m.),4 Bedrooms,4 Bathrooms,3 Balconies,Servant Room,"Sector 50 Gurgaon, Gurgaon, Haryana",7th of 18 Floors,East,5 to 10 Year Old,"['Baani Square', 'SS Plaza', 'Good Earth City ...",4bedroom 4800sq.Ft middle floor apartment avai...,"['4 Fan', '8 Light', 'No AC', 'No Bed', 'No Ch...","['Lift(s)', 'Water purifier', 'Swimming Pool',...","['Environment5 out of 5', 'Lifestyle5 out of 5..."
1973,1 BHK Flat in Sector 31 Gurgaon,raheja atlantis,Price on Request,NaN,Carpet area: 650 (60.39 sq.m.),1 Bedroom,1 Bathroom,1 Balcony,"Pooja Room,Study Room,Servant Room","Yes, Sector 31 Gurgaon, Gurgaon, Haryana",3rd of 15 Floors,East,0 to 1 Year Old,"['Huda Metro Station', 'Reliance Fresh, Indira...",It is my property and good condition and good ...,NaN,"['Feng Shui / Vaastu Compliant', 'Security / F...","['Green Area4 out of 5', 'Construction4 out of..."
2055,2 BHK Flat in Sector 79 Gurgaon,supertech araville,Price on Request,NaN,Built Up area: 1295 (120.31 sq.m.),2 Bedrooms,2 Bathrooms,No Balcony,NaN,"Sector 79, Sector 79 Gurgaon, Gurgaon, Haryana",15th of 15 Floors,NaN,undefined,NaN,"2 bath, unfurnished, 15th floor (Of 18), super...",NaN,NaN,"['Environment4 out of 5', 'Lifestyle3 out of 5..."
2358,2 BHK Flat in Sector 37D Gurgaon,the millennia 2,Price on Request,NaN,Carpet area: 552 (51.28 sq.m.),2 Bedrooms,1 Bathroom,1 Balcony,NaN,"Sector 37D Gurgaon, Gurgaon, Haryana",13rd of 13 Floors,NaN,undefined,"['Shri Balaji Hospital and Trauma Center', 'Sh...","1 bath, unfurnished, 13th floor (Of 13), at se...",NaN,NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."
2523,2 BHK Flat in Sector 95A Gurgaon,the roselia 2,Price on Request,NaN,Carpet area: 593 (55.09 sq.m.),2 Bedrooms,2 Bathrooms,2 Balconies,NaN,"Sector 95a, Pataudi Road, Sector 95A Gurgaon, ...",14th of 14 Floors,NaN,undefined,NaN,Best in class property available at sector 95a...,NaN,NaN,"['Environment5 out of 5', 'Lifestyle4.5 out of..."
2550,3 BHK Flat in Sector-2 Sohna,supertech hilltown,Price on Request,NaN,Built Up area: 1720 (159.79 sq.m.),3 Bedrooms,3 Bathrooms,3 Balconies,NaN,"Sohna Sector 2,gurgaon, Sector-2 Sohna, Gurgao...",4th of 4 Floors,North-East,undefined,NaN,"3 bath, unfurnished, 4th floor (Of 4), overloo...",NaN,NaN,NaN
2641,2 BHK Flat in Sector 95A Gurgaon,the roselia 2,Price on Request,NaN,Carpet area: 593 (55.09 sq.m.),2 Bedrooms,2 Bathrooms,2 Balconies,NaN,"Sector 95a, Pataudi Road, Sector 95A Gurgaon, ...",14th of 14 Floors,NaN,undefined,NaN,Best in class property available at sector 95a...,NaN,NaN,"['Environment5 out of 5', 'Safety5 out of 5', ..."
2960,3 BHK Flat in Sector 104 Gurgaon,godrej summit,Price on Request,NaN,Super Built up area 1647(153.01 sq.m.)Carpet a...,3 Bedrooms,3 Bathrooms,3 Balconies,NaN,"1402, Sector 104 Gurgaon, Gurgaon, Haryana",14th of 17 Floors,NaN,1 to 5 Year Old,"['MG Road Metro Station', 'The Esplanade Mall'...",We are the proud owners of this 3 bhk apartmen...,[],"['Intercom Facility', 'Lift(s)', 'Maintenance ...","['Management3 out of 5', 'Green Area4.5 out of..."
2973,4 BHK Flat in Gwal Pahari,krrish provence estate,Price on Request,NaN,Built Up area: 5800 (538.84 sq.m.),4 Bedrooms,5 Bathrooms,1 Balcony,NaN,"Gwal Pahari, Gurgaon, Haryana",17th of 24 Floors,NaN,Under Construction,"['Tniy Toons School', 'Pathways School Gurgoan...",Residential apartment for sell.Located on 17th...,NaN,NaN,NaN
2974,4 BHK Flat in Sector 95 Gurgaon,sidhartha ncr one phase,Price on Request,NaN,Super Built up area 2354(218.69 sq.m.),4 Bedrooms,4 Bathrooms,3+ Balconies,NaN,"Sector 95 Gurgaon, Gurgaon, Haryana",Ground of 3 Floors,North,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...","North facing entry, Very good layout, Excellen...",[],"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Management4 out of 5', 'Green Area4 out of 5..."

In [52]:
df = df[df['price'] != 'Price on Request']

In [53]:
df.head()

,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Krishna Colony,maa bhagwati residency,45 Lac,"₹ 5,000/sq.ft.",Carpet area: 900 (83.61 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"Krishna Colony, Gurgaon, Haryana",4th of 4 Floors,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ..."
1,2 BHK Flat in Ashok Vihar,apna enclave,50 Lac,"₹ 7,692/sq.ft.",Carpet area: 650 (60.39 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"46b, Ashok Vihar, Gurgaon, Haryana",1st of 3 Floors,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ..."
2,2 BHK Flat in Sohna,tulsiani easy in homes,40 Lac,"₹ 6,722/sq.ft.",Carpet area: 595 (55.28 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,NaN,"Sohna, Gurgaon, Haryana",12nd of 14 Floors,NaN,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment4 out of 5', 'Safety4 out of 5', ..."
3,2 BHK Flat in Sector 61 Gurgaon,smart world orchard,1.47 Crore,"₹ 12,250/sq.ft.",Carpet area: 1200 (111.48 sq.m.),2 Bedrooms,2 Bathrooms,2 Balconies,Study Room,"Sector 61 Gurgaon, Gurgaon, Haryana",2nd of 4 Floors,NaN,Dec 2023,"['Sector 55-56 Metro station', 'Bestech Centra...",Near to metro station of sector 56 and opposit...,NaN,"['Security / Fire Alarm', 'Private Garden / Te...",NaN
4,2 BHK Flat in Sector 92 Gurgaon,parkwood westend,70 Lac,"₹ 5,204/sq.ft.",Super Built up area 1345(124.95 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,Study Room,"Sector 92 Gurgaon, Gurgaon, Haryana",5th of 8 Floors,NaN,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",We are the proud owners of this 2 bhk alongwit...,[],NaN,"['Environment5 out of 5', 'Safety3 out of 5', ..."

In [54]:
def treat_price(x):
    if not isinstance(x, list) or len(x) < 2:
        return None      # or np.nan

    if x[1] == 'Lac':
        return round(float(x[0]) / 100, 2)

    elif x[1] == 'Cr':
        return float(x[0])

    else:
        return None

In [55]:
df['price'] = df['price'].str.split(' ').apply(treat_price)

In [56]:
df.head(5)

,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Krishna Colony,maa bhagwati residency,0.45,"₹ 5,000/sq.ft.",Carpet area: 900 (83.61 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"Krishna Colony, Gurgaon, Haryana",4th of 4 Floors,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ..."
1,2 BHK Flat in Ashok Vihar,apna enclave,0.50,"₹ 7,692/sq.ft.",Carpet area: 650 (60.39 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"46b, Ashok Vihar, Gurgaon, Haryana",1st of 3 Floors,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ..."
2,2 BHK Flat in Sohna,tulsiani easy in homes,0.40,"₹ 6,722/sq.ft.",Carpet area: 595 (55.28 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,NaN,"Sohna, Gurgaon, Haryana",12nd of 14 Floors,NaN,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment4 out of 5', 'Safety4 out of 5', ..."
3,2 BHK Flat in Sector 61 Gurgaon,smart world orchard,NaN,"₹ 12,250/sq.ft.",Carpet area: 1200 (111.48 sq.m.),2 Bedrooms,2 Bathrooms,2 Balconies,Study Room,"Sector 61 Gurgaon, Gurgaon, Haryana",2nd of 4 Floors,NaN,Dec 2023,"['Sector 55-56 Metro station', 'Bestech Centra...",Near to metro station of sector 56 and opposit...,NaN,"['Security / Fire Alarm', 'Private Garden / Te...",NaN
4,2 BHK Flat in Sector 92 Gurgaon,parkwood westend,0.70,"₹ 5,204/sq.ft.",Super Built up area 1345(124.95 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,Study Room,"Sector 92 Gurgaon, Gurgaon, Haryana",5th of 8 Floors,NaN,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",We are the proud owners of this 2 bhk alongwit...,[],NaN,"['Environment5 out of 5', 'Safety3 out of 5', ..."

In [57]:
# price_per_sqft
df['price_per_sqft'].value_counts()

price_per_sqft
₹ 10,000/sq.ft.     19
₹ 8,000/sq.ft.      16
₹ 12,500/sq.ft.     16
₹ 6,666/sq.ft.      13
₹ 5,000/sq.ft.      13
₹ 8,333/sq.ft.      12
₹ 7,500/sq.ft.      12
₹ 6,000/sq.ft.      11
₹ 8,461/sq.ft.       9
₹ 12,000/sq.ft.      8
₹ 7,000/sq.ft.       8
₹ 9,000/sq.ft.       8
₹ 11,111/sq.ft.      7
₹ 9,230/sq.ft.       6
₹ 8,888/sq.ft.       6
₹ 5,500/sq.ft.       6
₹ 6,578/sq.ft.       6
₹ 11,500/sq.ft.      6
₹ 8,928/sq.ft.       6
₹ 6,500/sq.ft.       5
₹ 11,428/sq.ft.      5
₹ 10,714/sq.ft.      5
₹ 16,000/sq.ft.      5
₹ 14,242/sq.ft.      5
₹ 5,384/sq.ft.       5
₹ 4,666/sq.ft.       5
₹ 8,205/sq.ft.       5
₹ 7,407/sq.ft.       5
₹ 7,692/sq.ft.       5
₹ 8,571/sq.ft.       5
₹ 7,142/sq.ft.       5
₹ 4,615/sq.ft.       5
₹ 7,641/sq.ft.       5
₹ 4,444/sq.ft.       5
₹ 5,600/sq.ft.       5
₹ 5,556/sq.ft.       5
₹ 8,108/sq.ft.       5
₹ 13,636/sq.ft.      4
₹ 8,784/sq.ft.       4
₹ 8,787/sq.ft.       4
₹ 13,913/sq.ft.      4
₹ 8,484/sq.ft.       4
₹ 15,384/sq.ft.      4
₹ 4,500/sq.ft.       4
₹ 14,418/sq.ft.      4
₹ 8,358/sq.ft.       4
₹ 7,317/sq.ft.       4
₹ 9,090/sq.ft.       4
₹ 4,854/sq.ft.       4
₹ 8,445/sq.ft.       4
₹ 6,735/sq.ft.       4
₹ 8,163/sq.ft.       4
₹ 8,500/sq.ft.       4
₹ 15,000/sq.ft.      4
₹ 8,139/sq.ft.       4
₹ 13,750/sq.ft.      4
₹ 10,416/sq.ft.      4
₹ 7,250/sq.ft.       4
₹ 9,822/sq.ft.       4
₹ 6,250/sq.ft.       4
₹ 16,666/sq.ft.      4
₹ 7,496/sq.ft.       4
₹ 9,210/sq.ft.       4
₹ 4,814/sq.ft.       4
₹ 5,660/sq.ft.       4
₹ 7,272/sq.ft.       4
₹ 7,812/sq.ft.       4
₹ 8,043/sq.ft.       4
₹ 4,687/sq.ft.       4
₹ 10,383/sq.ft.      4
₹ 11,666/sq.ft.      4
₹ 8,432/sq.ft.       4
₹ 8,474/sq.ft.       4
₹ 8,181/sq.ft.       3
₹ 13,000/sq.ft.      3
₹ 6,921/sq.ft.       3
₹ 13,870/sq.ft.      3
₹ 7,400/sq.ft.       3
₹ 14,254/sq.ft.      3
₹ 6,404/sq.ft.       3
₹ 5,238/sq.ft.       3
₹ 5,555/sq.ft.       3
₹ 10,555/sq.ft.      3
₹ 5,735/sq.ft.       3
₹ 9,473/sq.ft.       3
₹ 7,083/sq.ft.       3
₹ 16,969/sq.ft.      3
₹ 6,818/sq.ft.       3
₹ 9,900/sq.ft.       3
₹ 8,222/sq.ft.       3
₹ 8,078/sq.ft.       3
₹ 8,215/sq.ft.       3
₹ 7,150/sq.ft.       3
₹ 8,450/sq.ft.       3
₹ 8,080/sq.ft.       3
₹ 7,302/sq.ft.       3
₹ 7,467/sq.ft.       3
₹ 5,319/sq.ft.       3
₹ 6,387/sq.ft.       3
₹ 5,833/sq.ft.       3
₹ 14,430/sq.ft.      3
₹ 4,800/sq.ft.       3
₹ 7,549/sq.ft.       3
₹ 4,513/sq.ft.       3
₹ 6,593/sq.ft.       3
₹ 4,210/sq.ft.       3
₹ 9,615/sq.ft.       3
₹ 6,421/sq.ft.       3
₹ 11,000/sq.ft.      3
₹ 7,541/sq.ft.       3
₹ 7,750/sq.ft.       3
₹ 11,363/sq.ft.      3
₹ 7,954/sq.ft.       3
₹ 6,470/sq.ft.       3
₹ 6,086/sq.ft.       3
₹ 8,620/sq.ft.       3
₹ 10,638/sq.ft.      3
₹ 10,204/sq.ft.      3
₹ 5,325/sq.ft.       3
₹ 9,972/sq.ft.       3
₹ 6,644/sq.ft.       3
₹ 8,606/sq.ft.       3
₹ 6,476/sq.ft.       3
₹ 8,532/sq.ft.       3
₹ 4,820/sq.ft.       3
₹ 7,179/sq.ft.       3
₹ 9,011/sq.ft.       3
₹ 9,500/sq.ft.       3
₹ 7,586/sq.ft.       3
₹ 7,056/sq.ft.       3
₹ 6,542/sq.ft.       3
₹ 8,400/sq.ft.       3
₹ 5,878/sq.ft.       3
₹ 5,397/sq.ft.       3
₹ 5,856/sq.ft.       3
₹ 7,865/sq.ft.       3
₹ 7,948/sq.ft.       3
₹ 16,470/sq.ft.      3
₹ 8,886/sq.ft.       3
₹ 14,000/sq.ft.      3
₹ 9,904/sq.ft.       3
₹ 8,604/sq.ft.       3
₹ 8,148/sq.ft.       3
₹ 10,500/sq.ft.      3
₹ 13,392/sq.ft.      3
₹ 4,105/sq.ft.       3
₹ 6,667/sq.ft.       3
₹ 8,389/sq.ft.       3
₹ 10,139/sq.ft.      3
₹ 8,750/sq.ft.       3
₹ 8,433/sq.ft.       2
₹ 20,687/sq.ft.      2
₹ 10,018/sq.ft.      2
₹ 14,785/sq.ft.      2
₹ 12,022/sq.ft.      2
₹ 13,270/sq.ft.      2
₹ 19,767/sq.ft.      2
₹ 11,336/sq.ft.      2
₹ 15,416/sq.ft.      2
₹ 9,743/sq.ft.       2
₹ 9,166/sq.ft.       2
₹ 16,985/sq.ft.      2
₹ 6,422/sq.ft.       2
₹ 4,909/sq.ft.       2
₹ 8,897/sq.ft.       2
₹ 6,373/sq.ft.       2
₹ 8,504/sq.ft.       2
₹ 4,327/sq.ft.       2
₹ 15,263/sq.ft.      2
₹ 16,747/sq.ft.      2
₹ 8,290/sq.ft.       2
₹ 8,519/sq.ft.       2
₹ 18,271/sq.ft.      2
₹ 8,252/sq.ft.       2
₹ 7,780/sq.ft.       2
₹ 6,111/sq.ft.       2
₹ 7,585/sq.ft.       2
₹ 10,601/sq.ft.      2
₹ 5,882/sq.ft.       2
₹ 13,500/sq.ft.      2
₹ 9,909/sq.ft.       2
₹ 9,876/sq.ft.       2
₹ 11,724/sq.ft.      2
₹ 9,791/sq.ft.       2
₹ 5,671/sq.ft.       2
₹ 19,882/sq.ft.      2
₹ 7,174/sq.ft.       2
₹ 6,938/sq.ft.       2
₹ 11,715/sq.ft.      2
₹ 5,150/sq.ft.       2
₹ 15,500/sq.ft.      2
₹ 6,076/sq.ft.       2
₹ 7,490/sq.ft.       2
₹ 7,097/sq.ft.       2
₹ 9,620/sq.ft.       2
₹ 6,506/sq.ft.       2
₹ 9,025/sq.ft.       2
₹ 5,517/sq.ft.       2
₹ 6,428/sq.ft.       2
₹ 5,100/sq.ft.       2
₹ 6,510/sq.ft.       2
₹ 41,245/sq.ft.      2
₹ 9,851/sq.ft.       2
₹ 8,075/sq.ft.       2
₹ 6,429/sq.ft.       2
₹ 6,377/sq.ft.       2
₹ 10,531/sq.ft.      2
₹ 5,038/sq.ft.       2
₹ 5,658/sq.ft.       2
₹ 11,992/sq.ft.      2
₹ 3,695/sq.ft.       2
₹ 9,978/sq.ft.       2
₹ 15,294/sq.ft.      2
₹ 9,286/sq.ft.       2
₹ 4,307/sq.ft.       2
₹ 11,250/sq.ft.      2
₹ 7,758/sq.ft.       2
₹ 7,863/sq.ft.       2
₹ 6,024/sq.ft.       2
₹ 18,000/sq.ft.      2
₹ 8,159/sq.ft.       2
₹ 7,058/sq.ft.       2
₹ 8,670/sq.ft.       2
₹ 8,974/sq.ft.       2
₹ 17,619/sq.ft.      2
₹ 8,206/sq.ft.       2
₹ 7,391/sq.ft.       2
₹ 16,960/sq.ft.      2
₹ 11,516/sq.ft.      2
₹ 6,686/sq.ft.       2
₹ 8,972/sq.ft.       2
₹ 8,053/sq.ft.       2
₹ 8,618/sq.ft.       2
₹ 9,449/sq.ft.       2
₹ 9,062/sq.ft.       2
₹ 6,217/sq.ft.       2
₹ 6,206/sq.ft.       2
₹ 8,517/sq.ft.       2
₹ 9,452/sq.ft.       2
₹ 6,927/sq.ft.       2
₹ 12,777/sq.ft.      2
₹ 5,786/sq.ft.       2
₹ 6,985/sq.ft.       2
₹ 5,111/sq.ft.       2
₹ 5,797/sq.ft.       2
₹ 6,983/sq.ft.       2
₹ 6,739/sq.ft.       2
₹ 6,325/sq.ft.       2
₹ 6,061/sq.ft.       2
₹ 6,190/sq.ft.       2
₹ 7,225/sq.ft.       2
₹ 9,600/sq.ft.       2
₹ 14,478/sq.ft.      2
₹ 4,651/sq.ft.       2
₹ 14,800/sq.ft.      2
₹ 8,072/sq.ft.       2
₹ 11,627/sq.ft.      2
₹ 6,318/sq.ft.       2
₹ 9,677/sq.ft.       2
₹ 8,720/sq.ft.       2
₹ 11,700/sq.ft.      2
₹ 6,551/sq.ft.       2
₹ 7,574/sq.ft.       2
₹ 7,727/sq.ft.       2
₹ 15,998/sq.ft.      2
₹ 11,529/sq.ft.      2
₹ 6,569/sq.ft.       2
₹ 6,361/sq.ft.       2
₹ 4,200/sq.ft.       2
₹ 14,257/sq.ft.      2
₹ 9,333/sq.ft.       2
₹ 14,214/sq.ft.      2
₹ 7,248/sq.ft.       2
₹ 13,333/sq.ft.      2
₹ 10,603/sq.ft.      2
₹ 6,178/sq.ft.       2
₹ 5,521/sq.ft.       2
₹ 5,681/sq.ft.       2
₹ 7,857/sq.ft.       2
₹ 13,224/sq.ft.      2
₹ 13,281/sq.ft.      2
₹ 7,825/sq.ft.       2
₹ 8,521/sq.ft.       2
₹ 10,384/sq.ft.      2
₹ 14,545/sq.ft.      2
₹ 10,526/sq.ft.      2
₹ 9,259/sq.ft.       2
₹ 11,333/sq.ft.      2
₹ 5,424/sq.ft.       2
₹ 10,699/sq.ft.      2
₹ 5,899/sq.ft.       2
₹ 16,608/sq.ft.      2
₹ 8,609/sq.ft.       2
₹ 13,769/sq.ft.      2
₹ 9,128/sq.ft.       2
₹ 7,530/sq.ft.       2
₹ 8,006/sq.ft.       2
₹ 8,310/sq.ft.       2
₹ 8,582/sq.ft.       2
₹ 14,583/sq.ft.      2
₹ 9,182/sq.ft.       2
₹ 12,782/sq.ft.      2
₹ 11,125/sq.ft.      2
₹ 6,597/sq.ft.       2
₹ 18,181/sq.ft.      2
₹ 4,271/sq.ft.       2
₹ 8,524/sq.ft.       2
₹ 6,588/sq.ft.       2
₹ 8,410/sq.ft.       2
₹ 10,516/sq.ft.      2
₹ 10,936/sq.ft.      2
₹ 13,991/sq.ft.      2
₹ 11,505/sq.ft.      2
₹ 8,279/sq.ft.       2
₹ 7,884/sq.ft.       2
₹ 7,185/sq.ft.       2
₹ 200,000/sq.ft.     2
₹ 8,600/sq.ft.       2
₹ 8,756/sq.ft.       2
₹ 9,482/sq.ft.       2
₹ 5,599/sq.ft.       2
₹ 4,745/sq.ft.       2
₹ 8,453/sq.ft.       2
₹ 8,166/sq.ft.       2
₹ 7,631/sq.ft.       2
₹ 11,726/sq.ft.      2
₹ 16,858/sq.ft.      2
₹ 13,430/sq.ft.      2
₹ 6,811/sq.ft.       2
₹ 9,022/sq.ft.       2
₹ 12,012/sq.ft.      2
₹ 11,028/sq.ft.      2
₹ 6,134/sq.ft.       2
₹ 10,370/sq.ft.      2
₹ 4,000/sq.ft.       2
₹ 58/sq.ft.          2
₹ 5,463/sq.ft.       2
₹ 9,263/sq.ft.       2
₹ 6,189/sq.ft.       2
₹ 13,709/sq.ft.      2
₹ 8,457/sq.ft.       2
₹ 5,454/sq.ft.       2
₹ 6,209/sq.ft.       2
₹ 5,284/sq.ft.       2
₹ 6,141/sq.ft.       2
₹ 5,614/sq.ft.       2
₹ 8,376/sq.ft.       2
₹ 5,177/sq.ft.       2
₹ 8,305/sq.ft.       2
₹ 6,382/sq.ft.       2
₹ 14,683/sq.ft.      2
₹ 14,303/sq.ft.      2
₹ 8,424/sq.ft.       2
₹ 7,987/sq.ft.       2
₹ 6,616/sq.ft.       2
₹ 5,649/sq.ft.       2
₹ 21,538/sq.ft.      2
₹ 6,243/sq.ft.       2
₹ 9,854/sq.ft.       2
₹ 10,666/sq.ft.      2
₹ 5,564/sq.ft.       2
₹ 7,200/sq.ft.       2
₹ 9,589/sq.ft.       2
₹ 13,383/sq.ft.      2
₹ 8,518/sq.ft.       2
₹ 5,189/sq.ft.       2
₹ 5,291/sq.ft.       2
₹ 5,980/sq.ft.       2
₹ 5,828/sq.ft.       2
₹ 6,702/sq.ft.       2
₹ 5,528/sq.ft.       2
₹ 4,857/sq.ft.       2
₹ 13,076/sq.ft.      2
₹ 6,987/sq.ft.       2
₹ 7,610/sq.ft.       2
₹ 7,350/sq.ft.       2
₹ 8,903/sq.ft.       2
₹ 7,846/sq.ft.       2
₹ 7,297/sq.ft.       2
₹ 6,353/sq.ft.       2
₹ 8,536/sq.ft.       2
₹ 19,000/sq.ft.      2
₹ 8,324/sq.ft.       2
₹ 4,761/sq.ft.       2
₹ 6,465/sq.ft.       2
₹ 4,400/sq.ft.       2
₹ 11,412/sq.ft.      2
₹ 6,153/sq.ft.       2
₹ 9,306/sq.ft.       2
₹ 8,024/sq.ft.       2
₹ 6,406/sq.ft.       2
₹ 6,839/sq.ft.       2
₹ 7,716/sq.ft.       2
₹ 5,982/sq.ft.       2
₹ 14,285/sq.ft.      2
₹ 5,470/sq.ft.       2
₹ 11,755/sq.ft.      2
₹ 6,679/sq.ft.       2
₹ 7,945/sq.ft.       2
₹ 6,049/sq.ft.       2
₹ 9,146/sq.ft.       2
₹ 16,363/sq.ft.      2
₹ 6,896/sq.ft.       2
₹ 9,742/sq.ft.       2
₹ 15,195/sq.ft.      2
₹ 5,929/sq.ft.       2
₹ 8,283/sq.ft.       2
₹ 8,411/sq.ft.       2
₹ 6,313/sq.ft.       2
₹ 19,747/sq.ft.      2
₹ 7,878/sq.ft.       2
₹ 8,814/sq.ft.       2
₹ 8,031/sq.ft.       2
₹ 5,744/sq.ft.       2
₹ 8,294/sq.ft.       2
₹ 7,396/sq.ft.       2
₹ 9,027/sq.ft.       2
₹ 9,950/sq.ft.       2
₹ 10,553/sq.ft.      2
₹ 9,074/sq.ft.       2
₹ 6,420/sq.ft.       2
₹ 8,237/sq.ft.       2
₹ 14,615/sq.ft.      2
₹ 9,550/sq.ft.       2
₹ 5,405/sq.ft.       2
₹ 3,477/sq.ft.       2
₹ 6,338/sq.ft.       2
₹ 8,412/sq.ft.       2
₹ 8,835/sq.ft.       2
₹ 6,812/sq.ft.       2
₹ 7,765/sq.ft.       2
₹ 5,128/sq.ft.       2
₹ 6,402/sq.ft.       2
₹ 9,020/sq.ft.       2
₹ 12,250/sq.ft.      2
₹ 5,808/sq.ft.       2
₹ 4,080/sq.ft.       2
₹ 10,237/sq.ft.      2
₹ 8,035/sq.ft.       2
₹ 8,947/sq.ft.       2
₹ 8,036/sq.ft.       2
₹ 5,683/sq.ft.       2
₹ 8,611/sq.ft.       2
₹ 7,850/sq.ft.       2
₹ 7,817/sq.ft.       2
₹ 10,599/sq.ft.      2
₹ 6,692/sq.ft.       2
₹ 5,252/sq.ft.       2
₹ 7,908/sq.ft.       2
₹ 9,007/sq.ft.       2
₹ 12,444/sq.ft.      2
₹ 8,733/sq.ft.       2
₹ 11,727/sq.ft.      2
₹ 10,489/sq.ft.      2
₹ 15,454/sq.ft.      2
₹ 6,571/sq.ft.       2
₹ 6,774/sq.ft.       2
₹ 9,565/sq.ft.       2
₹ 13,928/sq.ft.      2
₹ 9,672/sq.ft.       2
₹ 8,834/sq.ft.       2
₹ 5,896/sq.ft.       2
₹ 8,632/sq.ft.       2
₹ 9,797/sq.ft.       2
₹ 5,513/sq.ft.       2
₹ 9,922/sq.ft.       2
₹ 9,139/sq.ft.       2
₹ 7,359/sq.ft.       2
₹ 7,223/sq.ft.       2
₹ 10,596/sq.ft.      2
₹ 7,014/sq.ft.       2
₹ 5,641/sq.ft.       2
₹ 5,825/sq.ft.       2
₹ 5,056/sq.ft.       2
₹ 33,198/sq.ft.      2
₹ 10,545/sq.ft.      2
₹ 6,647/sq.ft.       2
₹ 9,642/sq.ft.       2
₹ 6,825/sq.ft.       2
₹ 13,343/sq.ft.      2
₹ 5,820/sq.ft.       2
₹ 6,789/sq.ft.       2
₹ 6,254/sq.ft.       2
₹ 10,651/sq.ft.      2
₹ 5,725/sq.ft.       2
₹ 6,967/sq.ft.       2
₹ 9,433/sq.ft.       2
₹ 7,751/sq.ft.       2
₹ 11,694/sq.ft.      2
₹ 7,627/sq.ft.       2
₹ 6,029/sq.ft.       2
₹ 7,782/sq.ft.       2
₹ 12,212/sq.ft.      2
₹ 13,108/sq.ft.      2
₹ 7,608/sq.ft.       2
₹ 6,655/sq.ft.       2
₹ 5,674/sq.ft.       2
₹ 9,105/sq.ft.       2
₹ 15,551/sq.ft.      2
₹ 3,911/sq.ft.       2
₹ 10,476/sq.ft.      2
₹ 6,333/sq.ft.       2
₹ 7,796/sq.ft.       2
₹ 9,135/sq.ft.       2
₹ 6,315/sq.ft.       2
₹ 6,859/sq.ft.       2
₹ 6,493/sq.ft.       2
₹ 6,129/sq.ft.       2
₹ 4,723/sq.ft.       2
₹ 4,818/sq.ft.       2
₹ 6,538/sq.ft.       2
₹ 6,950/sq.ft.       2
₹ 5,714/sq.ft.       2
₹ 15,151/sq.ft.      2
₹ 6,200/sq.ft.       2
₹ 11,574/sq.ft.      2
₹ 6,053/sq.ft.       2
₹ 4,856/sq.ft.       2
₹ 5,588/sq.ft.       2
₹ 8,100/sq.ft.       2
₹ 5,839/sq.ft.       2
₹ 6,455/sq.ft.       2
₹ 7,234/sq.ft.       2
₹ 18,518/sq.ft.      2
₹ 11,765/sq.ft.      2
₹ 12,222/sq.ft.      2
₹ 7,449/sq.ft.       2
₹ 17,039/sq.ft.      2
₹ 8,846/sq.ft.       2
₹ 14,237/sq.ft.      2
₹ 6,722/sq.ft.       2
₹ 6,089/sq.ft.       1
₹ 8,367/sq.ft.       1
₹ 4,942/sq.ft.       1
₹ 4,673/sq.ft.       1
₹ 6,007/sq.ft.       1
₹ 4,602/sq.ft.       1
₹ 4,345/sq.ft.       1
₹ 6,168/sq.ft.       1
₹ 8,863/sq.ft.       1
₹ 4,320/sq.ft.       1
₹ 10,410/sq.ft.      1
₹ 5,178/sq.ft.       1
₹ 4,744/sq.ft.       1
₹ 9,406/sq.ft.       1
₹ 5,407/sq.ft.       1
₹ 7,893/sq.ft.       1
₹ 10,005/sq.ft.      1
₹ 7,410/sq.ft.       1
₹ 6,400/sq.ft.       1
₹ 4,715/sq.ft.       1
₹ 9,872/sq.ft.       1
₹ 6,594/sq.ft.       1
₹ 5,007/sq.ft.       1
₹ 6,376/sq.ft.       1
₹ 6,919/sq.ft.       1
₹ 12,173/sq.ft.      1
₹ 4,938/sq.ft.       1
₹ 6,969/sq.ft.       1
₹ 4,792/sq.ft.       1
₹ 6,378/sq.ft.       1
₹ 3,571/sq.ft.       1
₹ 7,581/sq.ft.       1
₹ 11,052/sq.ft.      1
₹ 14,536/sq.ft.      1
₹ 12,127/sq.ft.      1
₹ 12,144/sq.ft.      1
₹ 10,994/sq.ft.      1
₹ 10,761/sq.ft.      1
₹ 15,469/sq.ft.      1
₹ 20,533/sq.ft.      1
₹ 6,523/sq.ft.       1
₹ 21,013/sq.ft.      1
₹ 7,437/sq.ft.       1
₹ 4,022/sq.ft.       1
₹ 3,935/sq.ft.       1
₹ 9,387/sq.ft.       1
₹ 9,117/sq.ft.       1
₹ 10,953/sq.ft.      1
₹ 7,886/sq.ft.       1
₹ 5,432/sq.ft.       1
₹ 4,786/sq.ft.       1
₹ 6,618/sq.ft.       1
₹ 9,846/sq.ft.       1
₹ 13,513/sq.ft.      1
₹ 8,823/sq.ft.       1
₹ 14,623/sq.ft.      1
₹ 9,227/sq.ft.       1
₹ 7,307/sq.ft.       1
₹ 6,389/sq.ft.       1
₹ 6,165/sq.ft.       1
₹ 9,310/sq.ft.       1
₹ 6,201/sq.ft.       1
₹ 8,298/sq.ft.       1
₹ 6,023/sq.ft.       1
₹ 11,739/sq.ft.      1
₹ 12,110/sq.ft.      1
₹ 6,215/sq.ft.       1
₹ 35,483/sq.ft.      1
₹ 7,403/sq.ft.       1
₹ 17,484/sq.ft.      1
₹ 12,169/sq.ft.      1
₹ 8,242/sq.ft.       1
₹ 6,514/sq.ft.       1
₹ 6,580/sq.ft.       1
₹ 6,708/sq.ft.       1
₹ 13,846/sq.ft.      1
₹ 13,875/sq.ft.      1
₹ 12,400/sq.ft.      1
₹ 7,146/sq.ft.       1
₹ 14,074/sq.ft.      1
₹ 13,888/sq.ft.      1
₹ 13,878/sq.ft.      1
₹ 14,557/sq.ft.      1
₹ 12,325/sq.ft.      1
₹ 9,133/sq.ft.       1
₹ 6,819/sq.ft.       1
₹ 17,285/sq.ft.      1
₹ 13,929/sq.ft.      1
₹ 24,211/sq.ft.      1
₹ 8,724/sq.ft.       1
₹ 6,953/sq.ft.       1
₹ 13,725/sq.ft.      1
₹ 5,499/sq.ft.       1
₹ 7,065/sq.ft.       1
₹ 9,980/sq.ft.       1
₹ 9,036/sq.ft.       1
₹ 6,286/sq.ft.       1
₹ 6,846/sq.ft.       1
₹ 6,002/sq.ft.       1
₹ 8,062/sq.ft.       1
₹ 5,930/sq.ft.       1
₹ 9,238/sq.ft.       1
₹ 14,179/sq.ft.      1
₹ 7,096/sq.ft.       1
₹ 13,671/sq.ft.      1
₹ 10,262/sq.ft.      1
₹ 10,224/sq.ft.      1
₹ 9,850/sq.ft.       1
₹ 8,825/sq.ft.       1
₹ 8,204/sq.ft.       1
₹ 13,758/sq.ft.      1
₹ 15,685/sq.ft.      1
₹ 10,028/sq.ft.      1
₹ 8,516/sq.ft.       1
₹ 6,060/sq.ft.       1
₹ 14,987/sq.ft.      1
₹ 6,052/sq.ft.       1
₹ 14,090/sq.ft.      1
₹ 8,679/sq.ft.       1
₹ 14,727/sq.ft.      1
₹ 10,365/sq.ft.      1
₹ 7,789/sq.ft.       1
₹ 14,068/sq.ft.      1
₹ 5,859/sq.ft.       1
₹ 4,531/sq.ft.       1
₹ 10,178/sq.ft.      1
₹ 9,203/sq.ft.       1
₹ 15,007/sq.ft.      1
₹ 9,051/sq.ft.       1
₹ 9,622/sq.ft.       1
₹ 13,528/sq.ft.      1
₹ 4,864/sq.ft.       1
₹ 6,265/sq.ft.       1
₹ 4,308/sq.ft.       1
₹ 3,953/sq.ft.       1
₹ 12,484/sq.ft.      1
₹ 14,983/sq.ft.      1
₹ 8,759/sq.ft.       1
₹ 8,839/sq.ft.       1
₹ 16,750/sq.ft.      1
₹ 16,580/sq.ft.      1
₹ 10,334/sq.ft.      1
₹ 9,266/sq.ft.       1
₹ 11,860/sq.ft.      1
₹ 4,836/sq.ft.       1
₹ 10,595/sq.ft.      1
₹ 8,646/sq.ft.       1
₹ 10,461/sq.ft.      1
₹ 10,080/sq.ft.      1
₹ 8,172/sq.ft.       1
₹ 12,571/sq.ft.      1
₹ 11,914/sq.ft.      1
₹ 8,998/sq.ft.       1
₹ 11,451/sq.ft.      1
₹ 6,242/sq.ft.       1
₹ 5,490/sq.ft.       1
₹ 8,922/sq.ft.       1
₹ 6,310/sq.ft.       1
₹ 10,162/sq.ft.      1
₹ 7,116/sq.ft.       1
₹ 10,727/sq.ft.      1
₹ 6,227/sq.ft.       1
₹ 10,147/sq.ft.      1
₹ 10,529/sq.ft.      1
₹ 12,372/sq.ft.      1
₹ 11,817/sq.ft.      1
₹ 6,530/sq.ft.       1
₹ 15,561/sq.ft.      1
₹ 19,174/sq.ft.      1
₹ 5,207/sq.ft.       1
₹ 8,875/sq.ft.       1
₹ 8,916/sq.ft.       1
₹ 5,597/sq.ft.       1
₹ 8,395/sq.ft.       1
₹ 10,037/sq.ft.      1
₹ 5,942/sq.ft.       1
₹ 16,266/sq.ft.      1
₹ 21,577/sq.ft.      1
₹ 11,713/sq.ft.      1
₹ 8,270/sq.ft.       1
₹ 11,218/sq.ft.      1
₹ 7,525/sq.ft.       1
₹ 6,801/sq.ft.       1
₹ 7,590/sq.ft.       1
₹ 15,531/sq.ft.      1
₹ 5,762/sq.ft.       1
₹ 6,852/sq.ft.       1
₹ 14,843/sq.ft.      1
₹ 12,846/sq.ft.      1
₹ 20,388/sq.ft.      1
₹ 13,580/sq.ft.      1
₹ 12,658/sq.ft.      1
₹ 5,418/sq.ft.       1
₹ 11,358/sq.ft.      1
₹ 12,599/sq.ft.      1
₹ 13,678/sq.ft.      1
₹ 5,004/sq.ft.       1
₹ 9,365/sq.ft.       1
₹ 8,704/sq.ft.       1
₹ 8,623/sq.ft.       1
₹ 5,973/sq.ft.       1
₹ 15,185/sq.ft.      1
₹ 12,152/sq.ft.      1
₹ 13,253/sq.ft.      1
₹ 12,190/sq.ft.      1
₹ 4,370/sq.ft.       1
₹ 4,355/sq.ft.       1
₹ 7,734/sq.ft.       1
₹ 6,961/sq.ft.       1
₹ 4,528/sq.ft.       1
₹ 8,580/sq.ft.       1
₹ 13,571/sq.ft.      1
₹ 11,686/sq.ft.      1
₹ 6,585/sq.ft.       1
₹ 7,230/sq.ft.       1
₹ 6,453/sq.ft.       1
₹ 13,352/sq.ft.      1
₹ 8,793/sq.ft.       1
₹ 6,625/sq.ft.       1
₹ 10,443/sq.ft.      1
₹ 10,786/sq.ft.      1
₹ 9,627/sq.ft.       1
₹ 10,041/sq.ft.      1
₹ 7,646/sq.ft.       1
₹ 7,443/sq.ft.       1
₹ 7,208/sq.ft.       1
₹ 8,553/sq.ft.       1
₹ 16,129/sq.ft.      1
₹ 11,764/sq.ft.      1
₹ 12,813/sq.ft.      1
₹ 9,584/sq.ft.       1
₹ 12,178/sq.ft.      1
₹ 10,853/sq.ft.      1
₹ 12,589/sq.ft.      1
₹ 10,799/sq.ft.      1
₹ 9,169/sq.ft.       1
₹ 9,655/sq.ft.       1
₹ 11,489/sq.ft.      1
₹ 6,424/sq.ft.       1
₹ 9,030/sq.ft.       1
₹ 8,023/sq.ft.       1
₹ 9,052/sq.ft.       1
₹ 4,746/sq.ft.       1
₹ 9,497/sq.ft.       1
₹ 10,954/sq.ft.      1
₹ 6,104/sq.ft.       1
₹ 6,019/sq.ft.       1
₹ 5,531/sq.ft.       1
₹ 9,039/sq.ft.       1
₹ 12,047/sq.ft.      1
₹ 7,072/sq.ft.       1
₹ 7,180/sq.ft.       1
₹ 18,126/sq.ft.      1
₹ 7,380/sq.ft.       1
₹ 9,512/sq.ft.       1
₹ 8,708/sq.ft.       1
₹ 8,818/sq.ft.       1
₹ 6,609/sq.ft.       1
₹ 5,607/sq.ft.       1
₹ 5,422/sq.ft.       1
₹ 16,959/sq.ft.      1
₹ 14,375/sq.ft.      1
₹ 3,152/sq.ft.       1
₹ 15,160/sq.ft.      1
₹ 11,438/sq.ft.      1
₹ 8,320/sq.ft.       1
₹ 7,167/sq.ft.       1
₹ 12,134/sq.ft.      1
₹ 7,339/sq.ft.       1
₹ 6,641/sq.ft.       1
₹ 11,233/sq.ft.      1
₹ 7,554/sq.ft.       1
₹ 8,813/sq.ft.       1
₹ 9,393/sq.ft.       1
₹ 7,928/sq.ft.       1
₹ 7,636/sq.ft.       1
₹ 5,026/sq.ft.       1
₹ 8,256/sq.ft.       1
₹ 6,851/sq.ft.       1
₹ 10,755/sq.ft.      1
₹ 6,932/sq.ft.       1
₹ 7,196/sq.ft.       1
₹ 15,418/sq.ft.      1
₹ 8,541/sq.ft.       1
₹ 10,645/sq.ft.      1
₹ 13,589/sq.ft.      1
₹ 9,563/sq.ft.       1
₹ 10,465/sq.ft.      1
₹ 5,887/sq.ft.       1
₹ 6,975/sq.ft.       1
₹ 11,227/sq.ft.      1
₹ 14,598/sq.ft.      1
₹ 15,510/sq.ft.      1
₹ 24,963/sq.ft.      1
₹ 4,961/sq.ft.       1
₹ 9,933/sq.ft.       1
₹ 6,888/sq.ft.       1
₹ 11,174/sq.ft.      1
₹ 10,841/sq.ft.      1
₹ 5,717/sq.ft.       1
₹ 5,867/sq.ft.       1
₹ 14,177/sq.ft.      1
₹ 10,174/sq.ft.      1
₹ 7,991/sq.ft.       1
₹ 11,470/sq.ft.      1
₹ 10,567/sq.ft.      1
₹ 12,788/sq.ft.      1
₹ 6,826/sq.ft.       1
₹ 9,528/sq.ft.       1
₹ 15,514/sq.ft.      1
₹ 14,563/sq.ft.      1
₹ 9,212/sq.ft.       1
₹ 6,661/sq.ft.       1
₹ 6,163/sq.ft.       1
₹ 10,901/sq.ft.      1
₹ 4,193/sq.ft.       1
₹ 3,309/sq.ft.       1
₹ 15,906/sq.ft.      1
₹ 11,294/sq.ft.      1
₹ 11,204/sq.ft.      1
₹ 6,459/sq.ft.       1
₹ 7,258/sq.ft.       1
₹ 6,653/sq.ft.       1
₹ 7,268/sq.ft.       1
₹ 12,567/sq.ft.      1
₹ 6,330/sq.ft.       1
₹ 6,649/sq.ft.       1
₹ 13,235/sq.ft.      1
₹ 13,837/sq.ft.      1
₹ 6,267/sq.ft.       1
₹ 5,747/sq.ft.       1
₹ 7,904/sq.ft.       1
₹ 8,648/sq.ft.       1
₹ 8,539/sq.ft.       1
₹ 8,458/sq.ft.       1
₹ 11,628/sq.ft.      1
₹ 11,338/sq.ft.      1

In [58]:
df[~df['price_per_sqft']
   .str.split('/')
   .str.get(0)
   .str.replace('₹','', regex=False)
   .str.replace(',','', regex=False)
   .str.strip()
   .str.match(r'^\d+(\.\d+)?$', na=False)]

,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
18,2 BHK Flat in Sector 93 Gurgaon,signature global orchard avenue 2,NaN,NaN,Carpet area: 577.11 (53.62 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,NaN,"L-1104, Sector 93 Gurgaon, Gurgaon, Haryana",11st of 14 Floors,East,Under Construction,"['Huda Metro Station', 'V3S Sapphire Ninety', ...",Looking for a budget-Friendly 2 bhk flat in a ...,NaN,"['Security / Fire Alarm', 'Feng Shui / Vaastu ...",NaN
286,property_name,society,NaN,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
2850,2 BHK Flat in Sector 107 Gurgaon,signature global solera,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [59]:
df = df[df['property_name'] != 'property_name']

In [60]:
df = df.dropna(how='all')

In [61]:
df.reset_index(drop=True, inplace=True)

In [62]:
print(df[df['property_name'] == 'property_name'])
print(df[df['price_per_sqft'] == 'area'])

Empty DataFrame
Columns: [property_name, society, price, price_per_sqft, areaWithType, bedRoom, bathroom, balcony, additionalRoom, address, floorNum, facing, agePossession, nearbyLocations, description, furnishDetails, features, rating]
Index: []
Empty DataFrame
Columns: [property_name, society, price, price_per_sqft, areaWithType, bedRoom, bathroom, balcony, additionalRoom, address, floorNum, facing, agePossession, nearbyLocations, description, furnishDetails, features, rating]
Index: []

In [63]:
print(df['price_per_sqft'].dtype)

object

In [64]:
print(df['price_per_sqft'].dtype)

print(df['price_per_sqft'].head(10))

print(df['price_per_sqft'].apply(type).value_counts())

object
0     ₹ 5,000/sq.ft.
1     ₹ 7,692/sq.ft.
2     ₹ 6,722/sq.ft.
3    ₹ 12,250/sq.ft.
4     ₹ 5,204/sq.ft.
5     ₹ 6,269/sq.ft.
6    ₹ 13,333/sq.ft.
7     ₹ 7,860/sq.ft.
8     ₹ 8,148/sq.ft.
9    ₹ 16,885/sq.ft.
Name: price_per_sqft, dtype: object
price_per_sqft
<class 'str'>      3014
<class 'float'>       2
Name: count, dtype: int64

In [65]:
df['price_per_sqft'] = df['price_per_sqft'].str.split('/').str.get(0).str.replace('₹','').str.replace(',','').str.strip().astype('float')

In [66]:
df.head()

,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Krishna Colony,maa bhagwati residency,0.45,5000.0,Carpet area: 900 (83.61 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"Krishna Colony, Gurgaon, Haryana",4th of 4 Floors,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ..."
1,2 BHK Flat in Ashok Vihar,apna enclave,0.50,7692.0,Carpet area: 650 (60.39 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"46b, Ashok Vihar, Gurgaon, Haryana",1st of 3 Floors,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ..."
2,2 BHK Flat in Sohna,tulsiani easy in homes,0.40,6722.0,Carpet area: 595 (55.28 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,NaN,"Sohna, Gurgaon, Haryana",12nd of 14 Floors,NaN,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment4 out of 5', 'Safety4 out of 5', ..."
3,2 BHK Flat in Sector 61 Gurgaon,smart world orchard,NaN,12250.0,Carpet area: 1200 (111.48 sq.m.),2 Bedrooms,2 Bathrooms,2 Balconies,Study Room,"Sector 61 Gurgaon, Gurgaon, Haryana",2nd of 4 Floors,NaN,Dec 2023,"['Sector 55-56 Metro station', 'Bestech Centra...",Near to metro station of sector 56 and opposit...,NaN,"['Security / Fire Alarm', 'Private Garden / Te...",NaN
4,2 BHK Flat in Sector 92 Gurgaon,parkwood westend,0.70,5204.0,Super Built up area 1345(124.95 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,Study Room,"Sector 92 Gurgaon, Gurgaon, Haryana",5th of 8 Floors,NaN,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",We are the proud owners of this 2 bhk alongwit...,[],NaN,"['Environment5 out of 5', 'Safety3 out of 5', ..."

In [67]:
# bedrooms
df['bedRoom'].value_counts()

bedRoom
3 Bedrooms    1437
2 Bedrooms     944
4 Bedrooms     478
1 Bedroom      104
5 Bedrooms      31
6 Bedrooms       3
Name: count, dtype: int64

In [68]:
df[df['bedRoom'].isnull()]

,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
2841,2 BHK Flat in Sector 107 Gurgaon,signature global solera,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2842,4 BHK Flat in Sector 53 Gurgaon,tulip monsella,NaN,33198.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2843,2 BHK Flat in New Palam Vihar,my home,NaN,4400.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2844,2 BHK Flat in Sohna,breez global hill view,NaN,5470.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2914,3 BHK Flat in Sector 99A Gurgaon,pareena coban residences,NaN,5759.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2915,1 BHK Flat in Golf Course Ext Road,ikon tower baani city centre,NaN,12437.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2916,2 BHK Flat in Sector 89 Gurgaon,greenopolis,NaN,4820.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2918,4 BHK Flat in C Block Sushant Lok Phase 1,maple heights,NaN,8888.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2919,2 BHK Flat in Sector 99 Gurgaon,assotech blith,NaN,6593.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2982,4 BHK Flat in DLF Phase 4,chanderlok society,NaN,7234.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2983,3 BHK Flat in Sector 9A Gurgaon,jammu and kashmir bank employees cghs,NaN,6129.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2984,3 BHK Flat in Sector 37C Gurgaon,ild greens,NaN,4723.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2985,3 BHK Flat in Adarsh Nagar,ss residency,NaN,4818.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2986,3 BHK Flat in Rajendra Park,uphar lakshya homes,NaN,4200.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2987,2 BHK Flat in Sector 79 Gurgaon,supertech araville,NaN,9000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2988,3 BHK Flat in Sector 37C Gurgaon,corona optus,NaN,6361.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2989,3 BHK Flat in Sector 78 Gurgaon,umang monsoon breeze,NaN,6493.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2990,3 BHK Flat in Sector 88A Gurgaon,godrej oasis,NaN,8108.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2991,"2 BHK Flat in Godrej Aria , sector 79 , Gurgaon","godrej aria , sector 79 , gurgaon",NaN,11111.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [69]:
df = df[~df['bedRoom'].isnull()]

In [70]:
df['bedRoom'] = df['bedRoom'].str.split(' ').str.get(0).astype('int')

In [71]:
df.head()

,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Krishna Colony,maa bhagwati residency,0.45,5000.0,Carpet area: 900 (83.61 sq.m.),2,2 Bathrooms,1 Balcony,NaN,"Krishna Colony, Gurgaon, Haryana",4th of 4 Floors,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ..."
1,2 BHK Flat in Ashok Vihar,apna enclave,0.50,7692.0,Carpet area: 650 (60.39 sq.m.),2,2 Bathrooms,1 Balcony,NaN,"46b, Ashok Vihar, Gurgaon, Haryana",1st of 3 Floors,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ..."
2,2 BHK Flat in Sohna,tulsiani easy in homes,0.40,6722.0,Carpet area: 595 (55.28 sq.m.),2,2 Bathrooms,3 Balconies,NaN,"Sohna, Gurgaon, Haryana",12nd of 14 Floors,NaN,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment4 out of 5', 'Safety4 out of 5', ..."
3,2 BHK Flat in Sector 61 Gurgaon,smart world orchard,NaN,12250.0,Carpet area: 1200 (111.48 sq.m.),2,2 Bathrooms,2 Balconies,Study Room,"Sector 61 Gurgaon, Gurgaon, Haryana",2nd of 4 Floors,NaN,Dec 2023,"['Sector 55-56 Metro station', 'Bestech Centra...",Near to metro station of sector 56 and opposit...,NaN,"['Security / Fire Alarm', 'Private Garden / Te...",NaN
4,2 BHK Flat in Sector 92 Gurgaon,parkwood westend,0.70,5204.0,Super Built up area 1345(124.95 sq.m.),2,2 Bathrooms,3 Balconies,Study Room,"Sector 92 Gurgaon, Gurgaon, Haryana",5th of 8 Floors,NaN,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",We are the proud owners of this 2 bhk alongwit...,[],NaN,"['Environment5 out of 5', 'Safety3 out of 5', ..."

In [72]:
# bathroom
df['bathroom'].value_counts()

bathroom
2 Bathrooms    1044
3 Bathrooms     989
4 Bathrooms     636
5 Bathrooms     169
1 Bathroom      112
6 Bathrooms      42
7 Bathrooms       5
Name: count, dtype: int64

In [73]:
df['bathroom'].isnull().sum()

np.int64(0)

In [74]:
df['bathroom'] = df['bathroom'].str.split(' ').str.get(0).astype('int')

In [75]:
df.head()

,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Krishna Colony,maa bhagwati residency,0.45,5000.0,Carpet area: 900 (83.61 sq.m.),2,2,1 Balcony,NaN,"Krishna Colony, Gurgaon, Haryana",4th of 4 Floors,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ..."
1,2 BHK Flat in Ashok Vihar,apna enclave,0.50,7692.0,Carpet area: 650 (60.39 sq.m.),2,2,1 Balcony,NaN,"46b, Ashok Vihar, Gurgaon, Haryana",1st of 3 Floors,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ..."
2,2 BHK Flat in Sohna,tulsiani easy in homes,0.40,6722.0,Carpet area: 595 (55.28 sq.m.),2,2,3 Balconies,NaN,"Sohna, Gurgaon, Haryana",12nd of 14 Floors,NaN,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment4 out of 5', 'Safety4 out of 5', ..."
3,2 BHK Flat in Sector 61 Gurgaon,smart world orchard,NaN,12250.0,Carpet area: 1200 (111.48 sq.m.),2,2,2 Balconies,Study Room,"Sector 61 Gurgaon, Gurgaon, Haryana",2nd of 4 Floors,NaN,Dec 2023,"['Sector 55-56 Metro station', 'Bestech Centra...",Near to metro station of sector 56 and opposit...,NaN,"['Security / Fire Alarm', 'Private Garden / Te...",NaN
4,2 BHK Flat in Sector 92 Gurgaon,parkwood westend,0.70,5204.0,Super Built up area 1345(124.95 sq.m.),2,2,3 Balconies,Study Room,"Sector 92 Gurgaon, Gurgaon, Haryana",5th of 8 Floors,NaN,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",We are the proud owners of this 2 bhk alongwit...,[],NaN,"['Environment5 out of 5', 'Safety3 out of 5', ..."

In [76]:
# balcony
df['balcony'].value_counts()

balcony
3 Balconies     974
3+ Balconies    862
2 Balconies     749
1 Balcony       315
No Balcony       97
Name: count, dtype: int64

In [77]:
df['balcony'].isnull().sum()

np.int64(0)

In [78]:
df['balcony'] = df['balcony'].str.split(' ').str.get(0).str.replace('No','0')

In [79]:
df.head()

,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Krishna Colony,maa bhagwati residency,0.45,5000.0,Carpet area: 900 (83.61 sq.m.),2,2,1,NaN,"Krishna Colony, Gurgaon, Haryana",4th of 4 Floors,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ..."
1,2 BHK Flat in Ashok Vihar,apna enclave,0.50,7692.0,Carpet area: 650 (60.39 sq.m.),2,2,1,NaN,"46b, Ashok Vihar, Gurgaon, Haryana",1st of 3 Floors,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ..."
2,2 BHK Flat in Sohna,tulsiani easy in homes,0.40,6722.0,Carpet area: 595 (55.28 sq.m.),2,2,3,NaN,"Sohna, Gurgaon, Haryana",12nd of 14 Floors,NaN,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment4 out of 5', 'Safety4 out of 5', ..."
3,2 BHK Flat in Sector 61 Gurgaon,smart world orchard,NaN,12250.0,Carpet area: 1200 (111.48 sq.m.),2,2,2,Study Room,"Sector 61 Gurgaon, Gurgaon, Haryana",2nd of 4 Floors,NaN,Dec 2023,"['Sector 55-56 Metro station', 'Bestech Centra...",Near to metro station of sector 56 and opposit...,NaN,"['Security / Fire Alarm', 'Private Garden / Te...",NaN
4,2 BHK Flat in Sector 92 Gurgaon,parkwood westend,0.70,5204.0,Super Built up area 1345(124.95 sq.m.),2,2,3,Study Room,"Sector 92 Gurgaon, Gurgaon, Haryana",5th of 8 Floors,NaN,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",We are the proud owners of this 2 bhk alongwit...,[],NaN,"['Environment5 out of 5', 'Safety3 out of 5', ..."

In [80]:
# additionalRoom
df['additionalRoom'].value_counts()

additionalRoom
Servant Room                                     629
Study Room                                       232
Others                                           179
Pooja Room                                       132
Study Room,Servant Room                           81
Store Room                                        76
Pooja Room,Servant Room                           60
Servant Room,Others                               52
Servant Room,Pooja Room                           30
Study Room,Others                                 27
Pooja Room,Study Room,Servant Room,Others         25
Pooja Room,Study Room,Servant Room                24
Servant Room,Store Room                           19
Pooja Room,Study Room                             13
Pooja Room,Study Room,Servant Room,Store Room     12
Servant Room,Study Room                            8
Study Room,Pooja Room                              8
Study Room,Servant Room,Store Room                 7
Pooja Room,Servant Room,Others                     6
Servant Room,Study Room,Pooja Room,Store Room      6
Pooja Room,Store Room                              6
Others,Servant Room                                6
Pooja Room,Others                                  6
Study Room,Servant Room,Others                     5
Pooja Room,Study Room,Store Room                   4
Pooja Room,Store Room,Study Room,Servant Room      4
Study Room,Pooja Room,Store Room                   3
Store Room,Servant Room                            3
Servant Room,Pooja Room,Study Room,Store Room      3
Servant Room,Others,Pooja Room                     2
Study Room,Servant Room,Pooja Room,Store Room      2
Servant Room,Study Room,Store Room                 2
Study Room,Pooja Room,Servant Room                 2
Servant Room,Others,Store Room,Pooja Room          2
Pooja Room,Study Room,Others                       2
Store Room,Pooja Room,Servant Room                 1
Pooja Room,Study Room,Store Room,Servant Room      1
Pooja Room,Servant Room,Study Room,Store Room      1
Servant Room,Pooja Room,Store Room                 1
Study Room,Servant Room,Store Room,Pooja Room      1
Study Room,Servant Room,Pooja Room                 1
Servant Room,Pooja Room,Store Room,Study Room      1
Study Room,Store Room                              1
Store Room,Study Room                              1
Servant Room,Pooja Room,Study Room                 1
Servant Room,Study Room,Pooja Room                 1
Others,Study Room                                  1
Servant Room,Study Room,Others                     1
Store Room,Pooja Room                              1
Name: count, dtype: int64

In [81]:
df['additionalRoom'].value_counts().shape

(49,)

In [82]:
df['additionalRoom'].isnull().sum()

np.int64(1305)

In [83]:
df['additionalRoom'].fillna('not available',inplace=True)

C:\Users\vyash\AppData\Local\Temp\ipykernel_10556\1615843200.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['additionalRoom'].fillna('not available',inplace=True)

In [84]:
df['additionalRoom'] = df['additionalRoom'].str.lower()

In [85]:
df.head()

,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Krishna Colony,maa bhagwati residency,0.45,5000.0,Carpet area: 900 (83.61 sq.m.),2,2,1,not available,"Krishna Colony, Gurgaon, Haryana",4th of 4 Floors,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ..."
1,2 BHK Flat in Ashok Vihar,apna enclave,0.50,7692.0,Carpet area: 650 (60.39 sq.m.),2,2,1,not available,"46b, Ashok Vihar, Gurgaon, Haryana",1st of 3 Floors,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ..."
2,2 BHK Flat in Sohna,tulsiani easy in homes,0.40,6722.0,Carpet area: 595 (55.28 sq.m.),2,2,3,not available,"Sohna, Gurgaon, Haryana",12nd of 14 Floors,NaN,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment4 out of 5', 'Safety4 out of 5', ..."
3,2 BHK Flat in Sector 61 Gurgaon,smart world orchard,NaN,12250.0,Carpet area: 1200 (111.48 sq.m.),2,2,2,study room,"Sector 61 Gurgaon, Gurgaon, Haryana",2nd of 4 Floors,NaN,Dec 2023,"['Sector 55-56 Metro station', 'Bestech Centra...",Near to metro station of sector 56 and opposit...,NaN,"['Security / Fire Alarm', 'Private Garden / Te...",NaN
4,2 BHK Flat in Sector 92 Gurgaon,parkwood westend,0.70,5204.0,Super Built up area 1345(124.95 sq.m.),2,2,3,study room,"Sector 92 Gurgaon, Gurgaon, Haryana",5th of 8 Floors,NaN,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",We are the proud owners of this 2 bhk alongwit...,[],NaN,"['Environment5 out of 5', 'Safety3 out of 5', ..."

In [86]:
# floor num
df['floorNum']

0              4th   of 4 Floors
1              1st   of 3 Floors
2            12nd   of 14 Floors
3              2nd   of 4 Floors
4              5th   of 8 Floors
5              3rd   of 3 Floors
6             5th   of 25 Floors
7            14th   of 27 Floors
8              2nd   of 3 Floors
9            31st   of 40 Floors
10             1st   of 4 Floors
11            4th   of 13 Floors
12            4th   of 15 Floors
13            3rd   of 20 Floors
14           13rd   of 13 Floors
15           25th   of 25 Floors
16            Ground of 1 Floors
17           Ground of 14 Floors
18           11st   of 14 Floors
19           12nd   of 13 Floors
20             4th   of 4 Floors
21           11st   of 22 Floors
22             4th   of 4 Floors
23           Ground of 14 Floors
24           10th   of 25 Floors
25             3rd   of 3 Floors
26           20th   of 20 Floors
27            5th   of 17 Floors
28            4th   of 12 Floors
29             4th   of 4 Floors
30             1st   of 4 Floors
31           12nd   of 12 Floors
32            8th   of 12 Floors
33           20th   of 20 Floors
34             8th   of 8 Floors
35           21st   of 24 Floors
36           Ground of 11 Floors
37            6th   of 19 Floors
38            1st   of 19 Floors
39             1st   of 3 Floors
40           12nd   of 17 Floors
41            6th   of 24 Floors
42            1st   of 25 Floors
43             2nd   of 4 Floors
44             1st   of 4 Floors
45            9th   of 29 Floors
46             5th   of 8 Floors
47           18th   of 32 Floors
48           29th   of 31 Floors
49             3rd   of 5 Floors
50            3rd   of 26 Floors
51            5th   of 18 Floors
52             1st   of 4 Floors
53            9th   of 12 Floors
54            6th   of 10 Floors
55             2nd   of 4 Floors
56           14th   of 14 Floors
57            1st   of 11 Floors
58            8th   of 14 Floors
59             2nd   of 2 Floors
60           12nd   of 12 Floors
61            4th   of 14 Floors
62            1st   of 18 Floors
63            7th   of 19 Floors
64             3rd   of 4 Floors
65            5th   of 20 Floors
66            9th   of 15 Floors
67           14th   of 17 Floors
68           14th   of 14 Floors
69           15th   of 20 Floors
70            6th   of 14 Floors
71            6th   of 14 Floors
72            2nd   of 12 Floors
73            3rd   of 11 Floors
74             2nd   of 4 Floors
75            4th   of 13 Floors
76             3rd   of 4 Floors
77            6th   of 14 Floors
78            8th   of 13 Floors
79             2nd   of 4 Floors
80             4th   of 4 Floors
81           Ground of 14 Floors
82           11st   of 11 Floors
83             1st   of 3 Floors
84           11st   of 13 Floors
85           21st   of 41 Floors
86            4th   of 13 Floors
87             2nd   of 5 Floors
88             2nd   of 3 Floors
89             4th   of 4 Floors
90           32nd   of 32 Floors
91             2nd   of 4 Floors
92             2nd   of 2 Floors
93             2nd   of 2 Floors
94           11st   of 11 Floors
95           23rd   of 26 Floors
96            6th   of 12 Floors
97            9th   of 20 Floors
98             1st   of 4 Floors
99            5th   of 15 Floors
100            43   of 47 Floors
101            1st   of 1 Floors
102            1st   of 4 Floors
103           1st   of 13 Floors
104          11st   of 12 Floors
105          14th   of 24 Floors
106           9th   of 30 Floors
107           8th   of 14 Floors
108            9th   of 9 Floors
109           2nd   of 12 Floors
110           4th   of 14 Floors
111          32nd   of 55 Floors
112            43   of 47 Floors
113           2nd   of 19 Floors
114            3rd   of 4 Floors
115           8th   of 22 Floors
116            3rd   of 4 Floors
117          20th   of 32 Floors
118           2nd   of 17 Floors
119        Basement of 28 Floors
120           4th   of 10 Floors
121           Ground of 4 Floors
122            3rd   of 4 Floors
123            4th   of 8 Floors
124            3rd   of 4 Floors
125           6th   of 20 Floors
126          13rd   of 13 Floors
127          13rd   of 13 Floors
128          16th   of 16 Floors
129            3rd   of 4 Floors
130           Ground of 1 Floors
131          11st   of 14 Floors
132           2nd   of 14 Floors
133          12nd   of 12 Floors
134            2nd   of 4 Floors
135           1st   of 18 Floors
136           4th   of 12 Floors
137          11st   of 13 Floors
138           5th   of 17 Floors
139           1st   of 25 Floors
140          12nd   of 16 Floors
141          16th   of 18 Floors
142            6th   of 6 Floors
143            2nd   of 2 Floors
144            3rd   of 4 Floors
145          11st   of 25 Floors
146          10th   of 18 Floors
147           2nd   of 25 Floors
148            4th   of 4 Floors
149          19th   of 41 Floors
150            1st   of 3 Floors
151            8th   of 8 Floors
152          18th   of 19 Floors
153          10th   of 16 Floors
154           7th   of 20 Floors
155           2nd   of 14 Floors
156          10th   of 10 Floors
157           5th   of 12 Floors
158          10th   of 20 Floors
159          20th   of 34 Floors
160          20th   of 22 Floors
161            3rd   of 4 Floors
162          13rd   of 14 Floors
163           3rd   of 19 Floors
164           7th   of 18 Floors
165            4th   of 4 Floors
166           4th   of 14 Floors
167            2nd   of 4 Floors
168           2nd   of 25 Floors
169           4th   of 14 Floors
170           3rd   of 19 Floors
171            1st   of 1 Floors
172            2nd   of 4 Floors
173          11st   of 15 Floors
174          11st   of 21 Floors
175          16th   of 22 Floors
176           8th   of 10 Floors
177           1st   of 35 Floors
178          18th   of 25 Floors
179           8th   of 15 Floors
180                          NaN
181           2nd   of 16 Floors
182          17th   of 17 Floors
183          23rd   of 28 Floors
184          10th   of 18 Floors
185          30th   of 32 Floors
186            4th   of 4 Floors
187            2nd   of 3 Floors
188           Ground of 3 Floors
189          Ground of 14 Floors
190            1st   of 4 Floors
191            1st   of 1 Floors
192          11st   of 36 Floors
193          11st   of 13 Floors
194           Ground of 3 Floors
195          19th   of 19 Floors
196          28th   of 28 Floors
197            4th   of 4 Floors
198            9th   of 9 Floors
199            7th   of 7 Floors
200         Basement of 4 Floors
201          15th   of 15 Floors
202           2nd   of 34 Floors
203          Ground of 14 Floors
204           9th   of 10 Floors
205           1st   of 15 Floors
206            1st   of 1 Floors
207           4th   of 34 Floors
208           4th   of 18 Floors
209           3rd   of 15 Floors
210            1st   of 4 Floors
211           1st   of 19 Floors
212     Lower Ground of 4 Floors
213          13rd   of 13 Floors
214           4th   of 40 Floors
215           6th   of 18 Floors
216          20th   of 47 Floors
217          27th   of 48 Floors
218            6th   of 7 Floors
219          33rd   of 48 Floors
220          35th   of 35 Floors
221          26th   of 47 Floors
222           Ground of 1 Floors
223            2nd   of 4 Floors
224           4th   of 14 Floors
225          10th   of 17 Floors
226          11st   of 14 Floors
227          10th   of 22 Floors
228          Ground of 24 Floors
229           3rd   of 12 Floors
230           7th   of 25 Floors
231           8th   of 14 Floors
232            2nd   of 4 Floors
233           3rd   of 18 Floors
234            1st   of 4 Floors
235           9th   of 14 Floors
236          14th   of 15 Floors
237            4th   of 4 Floors
238           8th   of 25 Floors
239          10th   of 14 Floors
240           3rd   of 14 Floors
241            3rd   of 4 Floors
242            2nd   of 4 Floors
243           3rd   of 14 Floors
244            7th   of 7 Floors
245            2nd   of 4 Floors
246           3rd   of 15 Floors
247           8th   of 34 Floors
248          12nd   of 14 Floors
249           8th   of 42 Floors
250            1st   of 4 Floors
251           1st   of 22 Floors
252          26th   of 34 Floors
253          21st   of 29 Floors
254           8th   of 32 Floors
255           2nd   of 14 Floors
256           1st   of 12 Floors
257            2nd   of 4 Floors
258          39th   of 40 Floors
259           1st   of 14 Floors
260           8th   of 10 Floors
261            2nd   of 3 Floors
262            3rd   of 4 Floors
263            7th   of 9 Floors
264           4th   of 15 Floors
265          22nd   of 24 Floors
266          14th   of 20 Floors
267          11st   of 15 Floors
268          17th   of 17 Floors
269           3rd   of 12 Floors
270          12nd   of 13 Floors
271           8th   of 19 Floors
272           3rd   of 14 Floors
273          14th   of 14 Floors
274            7th   of 7 Floors
275           9th   of 15 Floors
276           2nd   of 17 Floors
277            3rd   of 3 Floors
278            6th   of 6 Floors
279          16th   of 16 Floors
280          12nd   of 12 Floors
281            1st   of 1 Floors
282            4th   of 4 Floors
283          17th   of 17 Floors
284           7th   of 26 Floors
285          11st   of 30 Floors
286            4th   of 8 Floors
287           1st   of 14 Floors
288           6th   of 14 Floors
289            1st   of 3 Floors
290          17th   of 17 Floors
291            1st   of 7 Floors
292          16th   of 18 Floors
293          19th   of 40 Floors
294          31st   of 32 Floors
295          14th   of 22 Floors
296           5th   of 19 Floors
297            2nd   of 4 Floors
298            1st   of 4 Floors
299           1st   of 10 Floors
300          15th   of 32 Floors
301            1st   of 7 Floors
302            1st   of 2 Floors
303            2nd   of 3 Floors
304          11st   of 14 Floors
305           9th   of 26 Floors
306          33rd   of 42 Floors
307          14th   of 18 Floors
308            4th   of 4 Floors
309           5th   of 14 Floors
310          18th   of 18 Floors
311           1st   of 14 Floors
312          20th   of 23 Floors
313           9th   of 14 Floors
314          18th   of 19 Floors
315           8th   of 32 Floors
316           4th   of 15 Floors
317           9th   of 17 Floors
318            4th   of 8 Floors
319           1st   of 14 Floors
320           6th   of 14 Floors
321            1st   of 3 Floors
322          19th   of 40 Floors
323          31st   of 32 Floors
324           5th   of 19 Floors
325            1st   of 4 Floors
326           1st   of 10 Floors
327          15th   of 32 Floors
328            1st   of 7 Floors
329            1st   of 2 Floors
330            2nd   of 3 Floors
331          11st   of 14 Floors
332           9th   of 26 Floors
333          14th   of 18 Floors
334           5th   of 14 Floors
335           1st   of 14 Floors
336           9th   of 14 Floors
337          18th   of 19 Floors
338           4th   of 15 Floors
339           1st   of 44 Floors
340          20th   of 20 Floors
341          24th   of 31 Floors
342           2nd   of 15 Floors
343            4th   of 4 Floors
344          14th   of 14 Floors
345           9th   of 16 Floors
346          14th   of 15 Floors
347           4th   of 14 Floors
348          26th   of 30 Floors
349           2nd   of 16 Floors
350          14th   of 24 Floors
351          17th   of 17 Floors
352           2nd   of 14 Floors
353          25th   of 25 Floors
354           9th   of 22 Floors
355            4th   of 4 Floors
356           6th   of 17 Floors
357           5th   of 14 Floors
358           4th   of 14 Floors
359          14th   of 21 Floors
360          15th   of 19 Floors
361           7th   of 14 Floors
362            2nd   of 4 Floors
363          16th   of 20 Floors
364          24th   of 51 Floors
365          10th   of 20 Floors
366            2nd   of 4 Floors
367           2nd   of 12 Floors
368           2nd   of 24 Floors
369           1st   of 19 Floors
370           8th   of 18 Floors
371          12nd   of 22 Floors
372          18th   of 19 Floors
373            1st   of 4 Floors
374           2nd   of 36 Floors
375            3rd   of 4 Floors
376          11st   of 11 Floors
377           7th   of 20 Floors
378           5th   of 18 Floors
379           6th   of 12 Floors
380          19th   of 31 Floors
381          25th   of 25 Floors
382          10th   of 10 Floors
383          10th   of 10 Floors
384            3rd   of 9 Floors
385           8th   of 14 Floors
386           5th   of 12 Floors
387           4th   of 22 Floors
388           1st   of 35 Floors
389          10th   of 14 Floors
390          16th   of 24 Floors
391          10th   of 14 Floors
392            3rd   of 8 Floors
393          17th   of 19 Floors
394           9th   of 14 Floors
395          11st   of 26 Floors
396          19th   of 20 Floors
397          Ground of 16 Floors
398          Ground of 23 Floors
399           8th   of 26 Floors
400           4th   of 11 Floors
401          30th   of 32 Floors
402          16th   of 51 Floors
403          18th   of 21 Floors
404           2nd   of 10 Floors
405           7th   of 10 Floors
406            2nd   of 4 Floors
407          10th   of 10 Floors
408           9th   of 12 Floors
409           6th   of 10 Floors
410          14th   of 29 Floors
411          25th   of 36 Floors
412           7th   of 23 Floors
413           4th   of 14 Floors
414            7th   of 9 Floors
415          18th   of 32 Floors
416          12nd   of 17 Floors
417            3rd   of 4 Floors
418          21st   of 28 Floors
419          14th   of 28 Floors
420           5th   of 25 Floors
421           3rd   of 19 Floors
422          19th   of 24 Floors
423          10th   of 14 Floors
424            5th   of 9 Floors
425          10th   of 30 Floors
426           7th   of 14 Floors
427          11st   of 20 Floors
428           2nd   of 17 Floors
429            2nd   of 4 Floors
430           7th   of 14 Floors
431           6th   of 14 Floors
432          11st   of 17 Floors
433           9th   of 14 Floors
434            4th   of 4 Floors
435          14th   of 20 Floors
436            5th   of 5 Floors
437            1st   of 4 Floors
438          16th   of 27 Floors
439           1st   of 10 Floors
440          18th   of 32 Floors
441           6th   of 16 Floors
442           8th   of 13 Floors
443            4th   of 4 Floors
444           7th   of 27 Floors
445            9th   of 9 Floors
446            3rd   of 4 Floors
447          11st   of 18 Floors
448          17th   of 25 Floors
449           7th   of 42 Floors
450           5th   of 30 Floors
451          16th   of 32 Floors
452           2nd   of 16 Floors
453           8th   of 29 Floors
454            2nd   of 8 Floors
455           3rd   of 32 Floors
456           6th   of 26 Floors
457          Ground of 14 Floors
458           2nd   of 12 Floors
459          15th   of 40 Floors
460          10th   of 25 Floors
461          11st   of 30 Floors
462          10th   of 15 Floors
463           4th   of 12 Floors
464           3rd   of 18 Floors
465           9th   of 19 Floors
466           8th   of 16 Floors
467           7th   of 12 Floors
468           5th   of 12 Floors
469           7th   of 14 Floors
470           7th   of 14 Floors
471           9th   of 14 Floors
472           2nd   of 20 Floors
473           5th   of 18 Floors
474          11st   of 20 Floors
475           8th   of 11 Floors
476           7th   of 17 Floors
477          20th   of 26 Floors
478          10th   of 12 Floors
479           7th   of 29 Floors
480          10th   of 51 Floors
481          16th   of 21 Floors
482           8th   of 21 Floors
483           1st   of 14 Floors
484          18th   of 30 Floors
485          15th   of 30 Floors
486          25th   of 30 Floors
487           5th   of 29 Floors
488           9th   of 26 Floors
489           5th   of 26 Floors
490           7th   of 26 Floors
491           7th   of 26 Floors
492           7th   of 26 Floors
493          12nd   of 30 Floors
494           5th   of 15 Floors
495           4th   of 10 Floors
496           6th   of 10 Floors
497            3rd   of 6 Floors
498          10th   of 18 Floors
499          15th   of 28 Floors
500          15th   of 28 Floors
501          10th   of 14 Floors
502           9th   of 28 Floors
503          10th   of 15 Floors
504          10th   of 21 Floors
505           9th   of 12 Floors
506           Ground of 4 Floors
507            1st   of 2 Floors
508          11st   of 12 Floors
509          17th   of 24 Floors
510           1st   of 26 Floors
511          Ground of 18 Floors
512           7th   of 14 Floors
513            5th   of 8 Floors
514          12nd   of 29 Floors
515          14th   of 29 Floors
516          14th   of 29 Floors
517           9th   of 21 Floors
518          19th   of 29 Floors
519           8th   of 14 Floors
520          14th   of 29 Floors
521           8th   of 14 Floors
522            2nd   of 5 Floors
523           9th   of 13 Floors
524           5th   of 14 Floors
525          Ground of 14 Floors
526            6th   of 8 Floors
527          10th   of 19 Floors
528           6th   of 10 Floors
529           8th   of 18 Floors
530           9th   of 24 Floors
531           9th   of 26 Floors
532          12nd   of 17 Floors
533          11st   of 16 Floors
534           6th   of 16 Floors
535          15th   of 39 Floors
536           7th   of 12 Floors
537           8th   of 19 Floors
538           8th   of 26 Floors
539           3rd   of 26 Floors
540          10th   of 26 Floors
541           1st   of 26 Floors
542           4th   of 26 Floors
543           5th   of 12 Floors
544           2nd   of 12 Floors
545          20th   of 40 Floors
546          13rd   of 40 Floors
547           8th   of 40 Floors
548           8th   of 19 Floors
549          16th   of 19 Floors
550          12nd   of 18 Floors
551          10th   of 19 Floors
552           6th   of 15 Floors
553          16th   of 19 Floors
554           8th   of 16 Floors
555          12nd   of 15 Floors
556          12nd   of 18 Floors
557           5th   of 22 Floors
558           9th   of 42 Floors
559           7th   of 14 Floors
560           7th   of 12 Floors
561           7th   of 12 Floors
562           5th   of 16 Floors
563           8th   of 31 Floors
564           7th   of 21 Floors
565           5th   of 29 Floors
566           9th   of 30 Floors
567          11st   of 29 Floors
568          10th   of 19 Floors
569           6th   of 31 Floors
570            3rd   of 9 Floors
571          22nd   of 30 Floors
572           5th   of 20 Floors
573          15th   of 29 Floors
574           5th   of 14 Floors
575          Ground of 14 Floors
576           6th   of 14 Floors
577           1st   of 24 Floors
578            2nd   of 8 Floors
579          12nd   of 19 Floors
580          12nd   of 25 Floors
581           6th   of 17 Floors
582           8th   of 18 Floors
583            4th   of 5 Floors
584           5th   of 25 Floors
585           2nd   of 19 Floors
586          20th   of 30 Floors
587          12nd   of 14 Floors
588          18th   of 19 Floors
589           2nd   of 26 Floors
590           3rd   of 15 Floors
591           3rd   of 19 Floors
592          18th   of 51 Floors
593           7th   of 27 Floors
594          17th   of 19 Floors
595           8th   of 14 Floors
596           2nd   of 19 Floors
597           8th   of 19 Floors
598           9th   of 30 Floors
599           3rd   of 18 Floors
600          12nd   of 23 Floors
601          10th   of 28 Floors
602            2nd   of 5 Floors
603          Ground of 21 Floors
604           7th   of 16 Floors
605            2nd   of 9 Floors

In [87]:
df['floorNum'].isnull().sum()

np.int64(2)

In [88]:
df[df['floorNum'].isnull()]

,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
180,3 BHK Flat in Dwarka Expressway Gurgaon,experion heartsong,NaN,6150.0,Built Up area: 1758 (163.32 sq.m.),3,3,0,not available,"604, Tower B-3, 6th Floor,Sector 108, Dwarka E...",NaN,NaN,Under Construction,NaN,A property by one of the most reputed builders...,[],NaN,NaN
2758,2 BHK Flat in Sector 78 Gurgaon,nan,0.6,3692.0,Built Up area: 1625 (150.97 sq.m.),2,2,0,not available,"Gurgaon, Sector 78 Gurgaon, Gurgaon, Haryana",NaN,NaN,Under Construction,NaN,The property is under construction it's by rah...,[],NaN,"['Safety4 out of 5', 'Lifestyle4 out of 5', 'E..."

In [89]:
df['floorNum'] = df['floorNum'].str.split(' ').str.get(0).replace('Ground','0').str.replace('Basement','-1').str.replace('Lower','0').str.extract(r'(\d+)')

In [90]:
df.head()

,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Krishna Colony,maa bhagwati residency,0.45,5000.0,Carpet area: 900 (83.61 sq.m.),2,2,1,not available,"Krishna Colony, Gurgaon, Haryana",4,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ..."
1,2 BHK Flat in Ashok Vihar,apna enclave,0.50,7692.0,Carpet area: 650 (60.39 sq.m.),2,2,1,not available,"46b, Ashok Vihar, Gurgaon, Haryana",1,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ..."
2,2 BHK Flat in Sohna,tulsiani easy in homes,0.40,6722.0,Carpet area: 595 (55.28 sq.m.),2,2,3,not available,"Sohna, Gurgaon, Haryana",12,NaN,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment4 out of 5', 'Safety4 out of 5', ..."
3,2 BHK Flat in Sector 61 Gurgaon,smart world orchard,NaN,12250.0,Carpet area: 1200 (111.48 sq.m.),2,2,2,study room,"Sector 61 Gurgaon, Gurgaon, Haryana",2,NaN,Dec 2023,"['Sector 55-56 Metro station', 'Bestech Centra...",Near to metro station of sector 56 and opposit...,NaN,"['Security / Fire Alarm', 'Private Garden / Te...",NaN
4,2 BHK Flat in Sector 92 Gurgaon,parkwood westend,0.70,5204.0,Super Built up area 1345(124.95 sq.m.),2,2,3,study room,"Sector 92 Gurgaon, Gurgaon, Haryana",5,NaN,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",We are the proud owners of this 2 bhk alongwit...,[],NaN,"['Environment5 out of 5', 'Safety3 out of 5', ..."

In [91]:
# facing
df['facing'].value_counts()

facing
North-East    505
East          490
North         301
South         203
West          183
North-West    162
South-East    144
South-West    135
Name: count, dtype: int64

In [92]:
df['facing'].isnull().sum()

np.int64(874)

In [93]:
df['facing'] = df['facing'].fillna('NA')

In [94]:
df['facing'].value_counts()

facing
NA            874
North-East    505
East          490
North         301
South         203
West          183
North-West    162
South-East    144
South-West    135
Name: count, dtype: int64

In [95]:
print(df[['price', 'price_per_sqft']].dtypes)

price             float64
price_per_sqft    float64
dtype: object

In [96]:
df['price'] = pd.to_numeric(df['price'], errors='coerce')
df['price_per_sqft'] = pd.to_numeric(df['price_per_sqft'], errors='coerce')

In [97]:
df.insert(loc=4,column='area',value=round((df['price']*10000000)/df['price_per_sqft']))

In [98]:
df.insert(loc=1,column='property_type',value='flat')

In [99]:
df.head()

,property_name,property_type,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Krishna Colony,flat,maa bhagwati residency,0.45,5000.0,900.0,Carpet area: 900 (83.61 sq.m.),2,2,1,not available,"Krishna Colony, Gurgaon, Haryana",4,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ..."
1,2 BHK Flat in Ashok Vihar,flat,apna enclave,0.50,7692.0,650.0,Carpet area: 650 (60.39 sq.m.),2,2,1,not available,"46b, Ashok Vihar, Gurgaon, Haryana",1,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ..."
2,2 BHK Flat in Sohna,flat,tulsiani easy in homes,0.40,6722.0,595.0,Carpet area: 595 (55.28 sq.m.),2,2,3,not available,"Sohna, Gurgaon, Haryana",12,NA,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment4 out of 5', 'Safety4 out of 5', ..."
3,2 BHK Flat in Sector 61 Gurgaon,flat,smart world orchard,NaN,12250.0,NaN,Carpet area: 1200 (111.48 sq.m.),2,2,2,study room,"Sector 61 Gurgaon, Gurgaon, Haryana",2,NA,Dec 2023,"['Sector 55-56 Metro station', 'Bestech Centra...",Near to metro station of sector 56 and opposit...,NaN,"['Security / Fire Alarm', 'Private Garden / Te...",NaN
4,2 BHK Flat in Sector 92 Gurgaon,flat,parkwood westend,0.70,5204.0,1345.0,Super Built up area 1345(124.95 sq.m.),2,2,3,study room,"Sector 92 Gurgaon, Gurgaon, Haryana",5,NA,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",We are the proud owners of this 2 bhk alongwit...,[],NaN,"['Environment5 out of 5', 'Safety3 out of 5', ..."

In [100]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2997 entries, 0 to 3015
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   property_name    2997 non-null   object
 1   property_type    2997 non-null   object
 2   society          2997 non-null   object
 3   price            922 non-null    float64
 4   price_per_sqft   2996 non-null   float64
 5   area             922 non-null    float64
 6   areaWithType     2997 non-null   object
 7   bedRoom          2997 non-null   int64
 8   bathroom         2997 non-null   int64
 9   balcony          2997 non-null   object
 10  additionalRoom   2997 non-null   object
 11  address          2991 non-null   object
 12  floorNum         2995 non-null   object
 13  facing           2997 non-null   object
 14  agePossession    2996 non-null   object
 15  nearbyLocations  2906 non-null   object
 16  description      2997 non-null   object
 17  furnishDetails   2200 non-null   object
 18  features         2590 non-null   object
 19  rating           2668 non-null   object
dtypes: float64(3), int64(2), object(15)
memory usage: 491.7+ KB

In [101]:
df.shape

(2997, 20)

In [102]:
df.to_csv('../data/processed/flats_cleaned.csv',index=False)